      SUBROUTINE N95CPW (A,B,N)
C
C     HALO: THE WORD COPIES AND ZERO FILLS OF GINO'S PACK AND UNPACK
C     (MDS/PACK.F, MDS/UNPACK.F) FOR A RUN OF ELEMENTS THAT NEED NO
C     CONVERSION: A(1..N) = B(1..N), WORDS AS THEY ARE (THE ELEMENT
C     LOOPS COPY THEM ONE WORD AT A TIME AT -O0; THIS IS -O2, THE SAME
C     BITS). A AND B DO NOT OVERLAP (A USER ARRAY AND A GINO BUFFER).
C
      INTEGER          N,A(N),B(N),I
      DO 10 I = 1,N
      A(I) = B(I)
   10 CONTINUE
      RETURN
      END

      SUBROUTINE N95ZRW (A,N)
C
C     HALO: A(1..N) = 0, ALL BITS (UNPACK'S ZERO FILL OF A GAP)
C
      INTEGER          N,A(N),I
      DO 10 I = 1,N
      A(I) = 0
   10 CONTINUE
      RETURN
      END

      INTEGER FUNCTION N95NZR (A,NW,NMAX)
C
C     HALO: HOW MANY ELEMENTS OF NW WORDS, FROM A(1) ON AND AT MOST
C     NMAX, ARE NONZERO BEFORE THE FIRST ONE WHOSE WORDS ARE ALL ZERO -
C     PACK'S TEST (LOOP 110: A WORD .NE. 0) FOR EACH IN TURN
C
      INTEGER          NW,NMAX,A(NW,NMAX),I,K
      DO 20 I = 1,NMAX
      DO 10 K = 1,NW
      IF (A(K,I) .NE. 0) GO TO 20
   10 CONTINUE
      N95NZR = I - 1
      RETURN
   20 CONTINUE
      N95NZR = NMAX
      RETURN
      END

      INTEGER FUNCTION N95SRT (A,N)
C
C     HALO: 1 WHEN A(1) .LT. A(2) .LT. ... .LT. A(N), ELSE 0 - WHETHER
C     N95BSR MAY SEARCH A (GP4'S SORTED LIST OF DEPENDENT SILS)
C
      INTEGER          N,A(*),I
      N95SRT = 0
      DO 10 I = 2,N
      IF (A(I) .LE. A(I-1)) RETURN
   10 CONTINUE
      N95SRT = 1
      RETURN
      END

      INTEGER FUNCTION N95BSR (IX,A,N)
C
C     HALO: WHERE IX IS IN THE STRICTLY INCREASING A(1..N), OR 0 - THE
C     POSITION GP4'S LINEAR SEARCH (LOOP 570) FINDS, BY BISECTION
C
      INTEGER          IX,N,A(*),LO,HI,MID
      N95BSR = 0
      LO = 1
      HI = N
   10 IF (LO .GT. HI) RETURN
      MID = (LO+HI)/2
      IF (A(MID) .EQ. IX) GO TO 20
      IF (A(MID) .LT. IX) LO = MID + 1
      IF (A(MID) .GT. IX) HI = MID - 1
      GO TO 10
   20 N95BSR = MID
      RETURN
      END
