      PROGRAM HRFGEN
C HALO: Build-time generator: the rigid format library as Fortran.
C HALO:
C HALO:   NASTRAN reads its rigid formats -- the DMAP for every solution
C HALO:   sequence, in rf/ -- from disk at run time, from the directory
C HALO:   named RFDIR. That made rf/ a second thing that had to travel
C HALO:   with the executable, at a path short enough for a CHARACTER*72,
C HALO:   found by a search relative to argument zero that comes up empty
C HALO:   when the program is run by bare name from PATH.
C HALO:
C HALO:   So the library is compiled in. CMake runs this program at build
C HALO:   time with the output file name and then every file in rf/:
C HALO:
C HALO:       hrfgen hrflib.f rf/AERO10 rf/AERO11 ... rf/NASINFO
C HALO:
C HALO:   and it writes hrflib.f, which holds
C HALO:
C HALO:       SUBROUTINE HRFLIB ( DIR, IERR )   write every file into DIR
C HALO:       SUBROUTINE HRFDEL ( DIR )         delete them again
C HALO:
C HALO:   The main program calls HRFLIB with the scratch directory when
C HALO:   RFDIR is not set, and points RFDIR at it; RFOPEN then reads the
C HALO:   files exactly as it always has. Setting RFDIR in the environment
C HALO:   still overrides, for anyone editing DMAP.
C HALO:
C HALO:   Each line of each file becomes one WRITE of a character
C HALO:   constant. The constant is split into pieces of at most 40
C HALO:   characters joined with //, so that no generated line passes
C HALO:   column 72, and an apostrophe is doubled. That is the whole
C HALO:   encoding; there is no escape for anything else because the
C HALO:   files are plain ASCII, which is checked here. Trailing blanks
C HALO:   are dropped and a blank line is written as one blank, neither
C HALO:   of which a card reader can tell.
C HALO:
C HALO:   One subroutine per file, HRF001 upward, so that no single
C HALO:   routine is tens of thousands of statements long.
      CHARACTER*1024  OUTF, PATH
      CHARACTER*512   LINE
      CHARACTER*80    NAME
      CHARACTER*40    CHUNK
      CHARACTER*2     PIECE
      CHARACTER*6     RNAME
      INTEGER         NARG, NF, JF, LP, LN, LL, LC, K, KS, I, NL, IOS
      INTEGER         LPIECE
      LOGICAL         FIRST
      CHARACTER*1     BSLASH, C
      BSLASH = CHAR(92)
C
      NARG = IARGC()
      IF ( NARG .GE. 2 ) GO TO 5
      WRITE (0,'(A)') 'usage: hrfgen output.f rf/file ...'
      CALL EXIT ( 1 )
5     CALL GETARG ( 1, OUTF )
      NF = NARG - 1
      OPEN ( 20, FILE = OUTF, STATUS = 'REPLACE', IOSTAT = IOS )
      IF ( IOS .EQ. 0 ) GO TO 8
      WRITE (0,'(A,A)') 'hrfgen: cannot write ', OUTF(1:LEN_TRIM(OUTF))
      CALL EXIT ( 1 )
8     CONTINUE
      WRITE (20,'(A)') 'C HALO: GENERATED by utility/hrfgen.f at '
     &   // 'build time from rf/. Do not edit'
      WRITE (20,'(A)') 'C HALO:   The rigid format library as '
     &   // 'Fortran; see the header of hrfgen.f'
C
C     one subroutine per input file
C
      DO 100 JF = 1, NF
         CALL GETARG ( JF + 1, PATH )
         LP = LEN_TRIM ( PATH )
C        the file name is what follows the last separator
         KS = 0
         DO 10 K = LP, 1, -1
            IF ( PATH(K:K) .EQ. '/' .OR. PATH(K:K) .EQ. BSLASH ) THEN
               KS = K
               GO TO 12
            ENDIF
10       CONTINUE
12       NAME = PATH(KS+1:LP)
         LN = LEN_TRIM ( NAME )
         WRITE ( RNAME, '(A,I3.3)' ) 'HRF', JF
         OPEN ( 21, FILE = PATH(1:LP), STATUS = 'OLD', IOSTAT = IOS )
         IF ( IOS .EQ. 0 ) GO TO 15
         WRITE (0,'(A,A)') 'hrfgen: cannot read ', PATH(1:LP)
         CALL EXIT ( 1 )
15       CONTINUE
         WRITE (20,'(A)') '      SUBROUTINE ' // RNAME
     &      // ' ( DIR, IERR )'
         WRITE (20,'(A)') 'C HALO: rf/' // NAME(1:LN)
         WRITE (20,'(A)') '      CHARACTER*(*) DIR'
         WRITE (20,'(A)') '      INTEGER       IERR'
         WRITE (20,'(A)') '      IERR = 1'
         WRITE (20,'(A)') '      OPEN ( 98, FILE = DIR // ''/'
     &      // NAME(1:LN) // ''','
         WRITE (20,'(A)') '     &       STATUS = ''REPLACE'', '
     &      // 'ERR = 99 )'
         NL = 0
20       READ ( 21, '(A)', END = 50, IOSTAT = IOS ) LINE
         IF ( IOS .NE. 0 ) GO TO 50
         NL = NL + 1
         LL = LEN_TRIM ( LINE )
         IF ( LL .GT. 0 ) GO TO 25
         WRITE (20,'(A)') '      WRITE ( 98, 1 ) '' '''
         GO TO 20
25       CONTINUE
C        split the line into pieces of at most 40 characters, doubling
C        apostrophes, and never splitting a doubled pair
         CHUNK = ' '
         LC    = 0
         FIRST = .TRUE.
         DO 40 I = 1, LL
            C = LINE(I:I)
            IF ( ICHAR(C) .LT. 32 .OR. ICHAR(C) .GT. 126 ) THEN
               WRITE (0,'(A,A,A,I6)') 'hrfgen: non-ASCII byte in ',
     &            PATH(1:LP), ' line', NL
               CALL EXIT ( 1 )
            ENDIF
            IF ( C .EQ. '''' ) THEN
               PIECE  = ''''''
               LPIECE = 2
            ELSE
               PIECE  = C
               LPIECE = 1
            ENDIF
            IF ( LC + LPIECE .LE. 40 ) GO TO 30
C           flush the chunk, continued
            IF ( FIRST ) THEN
               WRITE (20,'(A)') '      WRITE ( 98, 1 ) '''
     &            // CHUNK(1:LC) // '''//'
            ELSE
               WRITE (20,'(A)') '     &''' // CHUNK(1:LC) // '''//'
            ENDIF
            FIRST = .FALSE.
            CHUNK = ' '
            LC    = 0
30          CHUNK(LC+1:LC+LPIECE) = PIECE(1:LPIECE)
            LC = LC + LPIECE
40       CONTINUE
C        the last chunk closes the statement
         IF ( FIRST ) THEN
            WRITE (20,'(A)') '      WRITE ( 98, 1 ) '''
     &         // CHUNK(1:LC) // ''''
         ELSE
            WRITE (20,'(A)') '     &''' // CHUNK(1:LC) // ''''
         ENDIF
         GO TO 20
50       CLOSE ( 21 )
         WRITE (20,'(A)') '      CLOSE ( 98 )'
         WRITE (20,'(A)') '      IERR = 0'
         WRITE (20,'(A)') '99    RETURN'
         WRITE (20,'(A)') '1     FORMAT ( A )'
         WRITE (20,'(A)') '      END'
         WRITE (0,'(A,A,A,I6,A)') 'hrfgen: ', NAME(1:LN), ' ', NL,
     &      ' lines'
100   CONTINUE
C
C     HRFLIB writes them all; HRFDEL removes them
C
      WRITE (20,'(A)') '      SUBROUTINE HRFLIB ( DIR, IERR )'
      WRITE (20,'(A)') 'C HALO: write the rigid format library built '
     &   // 'into this executable'
      WRITE (20,'(A)') 'C HALO:   into directory DIR. IERR is 0 on '
     &   // 'success.'
      WRITE (20,'(A)') '      CHARACTER*(*) DIR'
      WRITE (20,'(A)') '      INTEGER       IERR, LD'
      WRITE (20,'(A)') '      LD = LEN_TRIM ( DIR )'
      DO 110 JF = 1, NF
         WRITE ( RNAME, '(A,I3.3)' ) 'HRF', JF
         WRITE (20,'(A)') '      CALL ' // RNAME
     &      // ' ( DIR(1:LD), IERR )'
         WRITE (20,'(A)') '      IF ( IERR .NE. 0 ) RETURN'
110   CONTINUE
      WRITE (20,'(A)') '      RETURN'
      WRITE (20,'(A)') '      END'
      WRITE (20,'(A)') '      SUBROUTINE HRFDEL ( DIR )'
      WRITE (20,'(A)') 'C HALO: delete what HRFLIB wrote into DIR.'
      WRITE (20,'(A)') '      CHARACTER*(*) DIR'
      WRITE (20,'(A)') '      INTEGER       LD'
      WRITE (20,'(A)') '      LD = LEN_TRIM ( DIR )'
      DO 120 JF = 1, NF
         CALL GETARG ( JF + 1, PATH )
         LP = LEN_TRIM ( PATH )
         KS = 0
         DO 115 K = LP, 1, -1
            IF ( PATH(K:K) .EQ. '/' .OR. PATH(K:K) .EQ. BSLASH ) THEN
               KS = K
               GO TO 117
            ENDIF
115      CONTINUE
117      NAME = PATH(KS+1:LP)
         LN = LEN_TRIM ( NAME )
         WRITE (20,'(A)') '      CALL HDELF ( DIR(1:LD) // ''/'
     &      // NAME(1:LN) // ''' )'
120   CONTINUE
      WRITE (20,'(A)') '      RETURN'
      WRITE (20,'(A)') '      END'
      CLOSE ( 20 )
      END
