      SUBROUTINE AMPCZT (NT)
C
C     HALO: THE THREADS OPENBLAS USES FOR THE IN-CORE SOLVE (AMPCZS).
C     OPENBLAS BUILT WITH OPENMP READS ITS CEILING ON THREADS ONCE, IN
C     ITS OWN CONSTRUCTOR - AND IN A STATIC EXECUTABLE THAT RUNS BEFORE
C     LIBGOMP HAS READ OMP_NUM_THREADS, SO THE CEILING IT RECORDS IS 1
C     AND EVERY ZGETRF RUNS ON ONE THREAD WHATEVER THE ENVIRONMENT SAYS.
C     SETTING THE COUNT EXPLICITLY IS OPENBLAS'S OWN WAY ROUND THAT (AN
C     EXPLICIT SETTING IS USED AS IT STANDS). NT .LE. 0 LEAVES IT ALONE.
C
      INTEGER NT
      IF (NT .GT. 0) CALL OPENBLAS_SET_NUM_THREADS (NT)
      RETURN
      END
