      SUBROUTINE AMPCZS (AT,B,N,NOH,IPIV,IOK)
C
C     HALO: THE SOLVE OF AMPCZ - AT X = B, X IN PLACE OF B - IN A BUILD
C     WITHOUT LAPACK: THE BUILT-IN LU, AMPCZB.
C
      INTEGER          N,NOH,IPIV(N),IOK
      DOUBLE COMPLEX   AT(N,N),B(N,NOH)
      CALL AMPCZB (AT,B,N,NOH,IPIV,IOK)
      RETURN
      END

      SUBROUTINE AMPCZR (AT,B,N,NOH,IPIV,IOK,ISOLV)
C
C     HALO: THE SAME SOLVE FOR AMPK'S TASKS (THE BUILT-IN LU; INSIDE AN
C     OPENMP TASK ITS PARALLEL LOOPS RUN ON THE CALLING THREAD)
C
      INTEGER          N,NOH,IPIV(N),IOK,ISOLV
      DOUBLE COMPLEX   AT(N,N),B(N,NOH)
      CALL AMPCZB (AT,B,N,NOH,IPIV,IOK)
      RETURN
      END

      INTEGER FUNCTION AMPCZL ()
C
C     HALO: 0 - NO LAPACK IN THIS BUILD: AMPK'S AERODYNAMIC CACHE KEEPS
C     NO LU FACTORS (THE BUILT-IN LU FACTORS AND SOLVES IN ONE), AND
C     NEVER CALLS THE TWO BELOW
C
      AMPCZL = 0
      RETURN
      END

      SUBROUTINE AMPCZF (AT,N,IPIV,IOK)
      INTEGER          N,IPIV(N),IOK
      DOUBLE COMPLEX   AT(N,N)
      IOK = 0
      RETURN
      END

      SUBROUTINE AMPCZQ (AT,B,N,NOH,IPIV,IOK)
      INTEGER          N,NOH,IPIV(N),IOK
      DOUBLE COMPLEX   AT(N,N),B(N,NOH)
      IOK = 0
      RETURN
      END
