      SUBROUTINE AMPCZS (AT,B,N,NOH,IPIV,IOK)
C
C     HALO: THE SOLVE OF AMPCZ - AT X = B, X IN PLACE OF B - IN A BUILD
C     WITHOUT LAPACK: THE BUILT-IN LU, AMPCZB.
C
      INTEGER          N,NOH,IPIV(N),IOK
      DOUBLE COMPLEX   AT(N,N),B(N,NOH)
      CALL AMPCZB (AT,B,N,NOH,IPIV,IOK)
      RETURN
      END

      SUBROUTINE AMPCZR (AT,B,N,NOH,IPIV,IOK,ISOLV)
C
C     HALO: THE SAME SOLVE FOR AMPK'S TASKS (THE BUILT-IN LU; INSIDE AN
C     OPENMP TASK ITS PARALLEL LOOPS RUN ON THE CALLING THREAD)
C
      INTEGER          N,NOH,IPIV(N),IOK,ISOLV
      DOUBLE COMPLEX   AT(N,N),B(N,NOH)
      CALL AMPCZB (AT,B,N,NOH,IPIV,IOK)
      RETURN
      END
