      SUBROUTINE AMPCZS (AT,B,N,NOH,IPIV,IOK)
C
C     HALO: THE SOLVE OF AMPCZ - AT X = B, X IN PLACE OF B - THROUGH
C     LAPACK: ZGETRF (THE BLOCKED LU, PARTIAL PIVOTING BY ROWS ON THE
C     SAME |RE| + |IM| TEST AS THE BUILT IN ONE) AND ZGETRS FOR THE NOH
C     RIGHT HAND SIDES. COMPILED IN WHEN CMAKE IS GIVEN A LAPACK
C     (NASTRAN_LAPACK_LIBRARIES); THE LINUX BUILD LINKS OPENBLAS
C     STATICALLY, THREADED WITH THE SAME OPENMP AS THE REST (SO
C     OMP_NUM_THREADS, WHICH THE SOL 145 DRIVER SETS PER CHILD, IS ITS
C     THREAD COUNT TOO). THE UNBLOCKED LU OF AMPCZS_BUILTIN.F STREAMS
C     THE TRAILING MATRIX ONCE PER COLUMN AND IS BOUND BY MEMORY; THE
C     BLOCKED ONE WORKS OUT OF CACHE AT THE RATE OF ZGEMM. THE ANSWER IS
C     THE SAME TO THE ROUNDING OF A DIFFERENT ORDER OF OPERATIONS, IN
C     DOUBLE PRECISION, BEFORE AMPCZ1 PACKS IT TO THE TYPE OF QJH.
C     IOK = 0 WHEN A PIVOT VANISHES (INFO .GT. 0).
C
C     THE THREADS: N95_BLAS_THREADS WHEN SET (THE SOL 145 DRIVER SETS
C     IT PER CHILD), ELSE THE OPENMP COUNT, HANDED TO THE LAPACK BY
C     AMPCZT (AMPCZT_OPENBLAS.F SAYS WHY OPENBLAS HAS TO BE TOLD).
C
      INTEGER          N,NOH,IPIV(N),IOK,INFO,NT,IOS
      DOUBLE COMPLEX   AT(N,N),B(N,NOH)
      CHARACTER*16     ENVT
!$    INTEGER          OMP_GET_MAX_THREADS
C
      IOK  = 0
      NT   = 0
      ENVT = ' '
      CALL GETENV ('N95_BLAS_THREADS',ENVT)
      IF (ENVT .NE. ' ') READ (ENVT,*,IOSTAT=IOS) NT
      IF (ENVT .NE. ' ' .AND. IOS .NE. 0) NT = 0
!$    IF (NT .LE. 0) NT = OMP_GET_MAX_THREADS()
      CALL AMPCZT (NT)
      CALL ZGETRF (N,N,AT,N,IPIV,INFO)
      IF (INFO .NE. 0) RETURN
      CALL ZGETRS ('N',N,NOH,AT,N,IPIV,B,N,INFO)
      IF (INFO .NE. 0) RETURN
      IOK = 1
      RETURN
      END
