      SUBROUTINE AMPCZS (AT,B,N,NOH,IPIV,IOK)
C
C     HALO: THE SOLVE OF AMPCZ - AT X = B, X IN PLACE OF B - WHEN THE
C     BUILD HAS NO LAPACK: LU OF AT IN PLACE WITH PARTIAL PIVOTING,
C     THREADED WITH OPENMP. THE LOOPS AMPCZ1 HAD (THEY MOVED HERE WHEN
C     THE LAPACK BUILD, AMPCZS_LAPACK.F, WAS ADDED). IOK = 0 WHEN A
C     PIVOT VANISHES.
C
      INTEGER          N,NOH,IPIV(N),IOK
      DOUBLE COMPLEX   AT(N,N),B(N,NOH)
      DOUBLE PRECISION AMAX,T
      DOUBLE COMPLEX   R,S,ZERO
      INTEGER          I,J,K,IPK
C
      IOK  = 0
      ZERO = (0.D0,0.D0)
C
C     LU OF AT IN PLACE, PARTIAL PIVOTING BY ROWS: P*AT = L*U WITH
C     L UNIT LOWER TRIANGULAR BELOW THE DIAGONAL AND U ON AND ABOVE.
C     THE PIVOT ROW IS SWAPPED ACROSS ALL N COLUMNS SO THAT THE
C     INTERCHANGES CAN BE APPLIED TO A RIGHT HAND SIDE IN ORDER.
C     THE TRAILING UPDATE, WHERE THE TIME GOES, IS THREADED OVER ITS
C     COLUMNS WHEN THE BUILD HAS OPENMP.
C
      DO 200 K = 1,N
      IPK  = K
      AMAX = ABS(DBLE(AT(K,K))) + ABS(DIMAG(AT(K,K)))
      DO 110 I = K+1,N
      T = ABS(DBLE(AT(I,K))) + ABS(DIMAG(AT(I,K)))
      IF (T .LE. AMAX) GO TO 110
      AMAX = T
      IPK  = I
  110 CONTINUE
      IPIV(K) = IPK
      IF (AMAX .EQ. 0.D0) RETURN
      IF (IPK .EQ. K) GO TO 130
      DO 120 J = 1,N
      S = AT(K,J)
      AT(K,J)   = AT(IPK,J)
      AT(IPK,J) = S
  120 CONTINUE
  130 IF (K .EQ. N) GO TO 200
      R = (1.D0,0.D0)/AT(K,K)
      DO 140 I = K+1,N
  140 AT(I,K) = AT(I,K)*R
!$OMP PARALLEL DO PRIVATE(I,S) SCHEDULE(STATIC)
      DO 160 J = K+1,N
      S = AT(K,J)
      IF (S .NE. ZERO) THEN
         DO 150 I = K+1,N
  150    AT(I,J) = AT(I,J) - AT(I,K)*S
      END IF
  160 CONTINUE
!$OMP END PARALLEL DO
  200 CONTINUE
C
C     THE ROW INTERCHANGES ON B, THEN L*Y = P*B AND U*X = Y, A COLUMN
C     OF B AT A TIME (THE COLUMNS ARE INDEPENDENT, SO THREADED)
C
      DO 220 K = 1,N
      IPK = IPIV(K)
      IF (IPK .EQ. K) GO TO 220
      DO 210 J = 1,NOH
      S = B(K,J)
      B(K,J)   = B(IPK,J)
      B(IPK,J) = S
  210 CONTINUE
  220 CONTINUE
!$OMP PARALLEL DO PRIVATE(I,K,S) SCHEDULE(STATIC)
      DO 260 J = 1,NOH
      DO 240 K = 1,N
      S = B(K,J)
      IF (S .NE. ZERO) THEN
         DO 230 I = K+1,N
  230    B(I,J) = B(I,J) - AT(I,K)*S
      END IF
  240 CONTINUE
      DO 255 K = N,1,-1
      B(K,J) = B(K,J)/AT(K,K)
      S = B(K,J)
      DO 250 I = 1,K-1
  250 B(I,J) = B(I,J) - AT(I,K)*S
  255 CONTINUE
  260 CONTINUE
!$OMP END PARALLEL DO
C
      IOK = 1
      RETURN
      END
