      SUBROUTINE AMPCZT (NT)
C
C     HALO: THE THREADS OF THE LAPACK THE IN-CORE SOLVE (AMPCZS) CALLS,
C     FOR A LAPACK THAT IS NOT OPENBLAS: NOTHING TO SET - IT FOLLOWS ITS
C     OWN ENVIRONMENT (AMPCZT_OPENBLAS.F SAYS WHY OPENBLAS NEEDS
C     TELLING).
C
      INTEGER NT
      RETURN
      END
