      SUBROUTINE AETRIM
C
C     HALO: SOL 144, STATIC AEROELASTIC TRIM - THE DMAP MODULE AETRIM.
C     NEW IN THIS FORK (SOL144.MD HAS THE THEORY AND THE DESIGN). THIS
C     IS ITS GINO SIDE: EVERY DATA BLOCK IT IS GIVEN IS HANDED TO THE C
C     SIDE (MSC/MSCAEST.C) A RECORD OR A MATRIX COLUMN AT A TIME, THE C
C     SIDE DOES THE ALGEBRA, AND THE MATRICES AND THE PRINTED TABLES IT
C     RETURNS ARE WRITTEN HERE. THE TRIM CARDS THEMSELVES NEVER REACH
C     THE INPUT FILE PROCESSOR: THE MSC FRONT END READ THEM (MSCTRIM.C).
C
C     AETRIM  CASECC,USET,GTKA,GTKG,AJJL,SKJ,D1JK,ACPT,CLS,XM,MXM,DM,
C             MR,MDG,BGPDT,SIL,CSTMA,GPLA,USETA/O1,O2,O3,O4/MODE $
C
C     MODE 1  USET,GTKA,BGPDT,SIL,CSTMA         -> ES (L X NS), DG (G X 6)
C     MODE 2  ALL OF THEM                        -> PLA (L X NSUB),
C             UDDT (R X NSUB), PGT (G X NSUB), AND THE PRINT
C
      INTEGER         MODE,SYSBUF,NOUT,IP2,IP3,IP4,IP5,IBCD(2),
     1                UM,UO,UR,USG,USB,UL,UA,UF,US,UN,UG,UE,UP,UNE,UFE,
     2                UD,UPS,USA,UK,UPA,TWO1,IZ(1),NAME(2),IERR,IBUF,
     3                IKIND(19),IFILE,I,NL,IPAGE,LINE35(50),ITITLE(96),
     4                NLPP,LINE,NPAGE,J
      COMMON /BLANK / MODE,IP2,IP3,IP4,IP5,IBCD
      COMMON /SYSTEM/ SYSBUF,NOUT,ISKIP(6),NLPP,IST,NPAGE,LINE
      COMMON /BITPOS/ UM,UO,UR,USG,USB,UL,UA,UF,US,UN,UG,UE,UP,UNE,UFE,
     1                UD,UPS,USA,UK,UPA
      COMMON /TWO   / TWO1(32)
      COMMON /OUTPUT/ ITTL(32),ISUBT(32),ILABL(32),IHD(96)
      COMMON /ZZZZZZ/ Z(1)
      EQUIVALENCE     (Z(1),IZ(1))
      DATA    NAME  / 4HAETR,4HIM   /
C
C     THE KIND OF EACH INPUT, AS THE C SIDE NUMBERS THEM: 0 A TABLE,
C     1 A MATRIX, 2 AJJL (A HEADER RECORD, THEN THE MATRIX)
C
      DATA    IKIND / 0,0,1,1,2,1,1,0,1,1,1,1,1,1,0,0,0,0,0 /
C
      IBUF = KORSZ(Z) - SYSBUF - 1
      CALL N95TBT (TWO1(UA),TWO1(UL),TWO1(UR),TWO1(UK))
      CALL N95TA0 (MODE)
C
C     THE INPUTS. A PURGED ONE IS SIMPLY NOT HANDED OVER
C
      DO 100 I = 1,19
      IFILE = 100 + I
      IF (MODE.EQ.1 .AND. I.NE.2 .AND. I.NE.3 .AND. I.NE.15 .AND.
     1    I.NE.16 .AND. I.NE.17 .AND. I.NE.18) GO TO 100
      IF (IKIND(I) .EQ. 0) CALL AETRTB (IFILE,I,IZ,IBUF)
      IF (IKIND(I) .EQ. 1) CALL AETRMX (IFILE,I,IZ,IBUF,0)
      IF (IKIND(I) .EQ. 2) CALL AETRMX (IFILE,I,IZ,IBUF,1)
  100 CONTINUE
C
C     THE WORK
C
      CALL N95TRN (MODE,IERR)
C
C     THE PRINT: A LINE WHOSE PAGE IS 0 OR MORE STARTS A PAGE WITH THAT
C     SUBCASE'S TITLE, SUBTITLE AND LABEL
C
      CALL N95TNL (NL)
      DO 200 I = 1,NL
      CALL N95TLN (I,LINE35,IPAGE)
      IF (IPAGE .LT. 0) GO TO 150
      CALL N95TPG (IPAGE,ITITLE)
      DO 120 J = 1,32
      ITTL(J)  = ITITLE(J)
      ISUBT(J) = ITITLE(32+J)
      ILABL(J) = ITITLE(64+J)
  120 CONTINUE
      CALL PAGE1
      GO TO 200
  150 IF (LINE+1 .GT. NLPP) CALL PAGE1
      LINE = LINE + 1
      CALL AETRWL (NOUT,LINE35)
  200 CONTINUE
      IF (IERR .NE. 0) CALL MESAGE (-61,0,NAME)
C
C     THE OUTPUTS
C
      IF (MODE .EQ. 1) THEN
         CALL AETRWM (201,21,IZ,IBUF)
         CALL AETRWM (202,22,IZ,IBUF)
      ELSE
         CALL AETRWM (201,31,IZ,IBUF)
         CALL AETRWM (202,32,IZ,IBUF)
         CALL AETRWM (203,33,IZ,IBUF)
      ENDIF
      RETURN
      END
C
C
      SUBROUTINE AETRWL (NOUT,LINE35)
C
C     HALO: ONE PRINTED LINE, ITS TRAILING BLANKS LEFT OFF
C
      INTEGER         NOUT,LINE35(50),N
      CHARACTER*200   C
      DO 10 N = 1,50
      WRITE (C(4*N-3:4*N),'(A4)') LINE35(N)
   10 CONTINUE
      N = LEN_TRIM(C)
      IF (N .LT. 1) N = 1
      WRITE (NOUT,'(A)') C(1:N)
      RETURN
      END
C
C
      SUBROUTINE AETRTB (IFILE,KIND,IZ,IBUF)
C
C     HALO: EVERY RECORD OF THE TABLE IFILE TO THE C SIDE, AS KIND
C
      INTEGER         IFILE,KIND,IZ(1),IBUF,MCB(7),IREC,N,NZ
      MCB(1) = IFILE
      CALL RDTRL (MCB)
      IF (MCB(1) .LE. 0) RETURN
      NZ = IBUF - 1
      CALL GOPEN (IFILE,IZ(IBUF),0)
      IREC = 0
   10 CALL READ (*90,*20,IFILE,IZ,NZ,0,N)
      CALL MESAGE (-8,0,IFILE)
   20 IREC = IREC + 1
      CALL N95TBL (KIND,IREC,N,IZ)
      GO TO 10
   90 CALL CLOSE (IFILE,1)
      RETURN
      END
C
C
      SUBROUTINE AETRMX (IFILE,KIND,IZ,IBUF,IHDR)
C
C     HALO: THE MATRIX IFILE TO THE C SIDE A COLUMN AT A TIME, IN DOUBLE
C     PRECISION (DOUBLE COMPLEX WHEN IT IS COMPLEX). WITH IHDR = 1 THE
C     HEADER RECORD (AJJL'S M-K LIST) GOES FIRST, AS KIND 105.
C
      INTEGER         IFILE,KIND,IZ(1),IBUF,IHDR,MCB(7),NCOL,NROW,ICPX,
     1                J,N,NZ,ITC,II,JJ,INCR,KH,NW
      DOUBLE PRECISION, ALLOCATABLE :: COL(:)
      COMMON /UNPAKX/ ITC,II,JJ,INCR
      MCB(1) = IFILE
      CALL RDTRL (MCB)
      IF (MCB(1) .LE. 0) RETURN
      NCOL = MCB(2)
      NROW = MCB(3)
      ICPX = 0
      IF (MCB(5).EQ.3 .OR. MCB(5).EQ.4) ICPX = 1
      NZ = IBUF - 1
      IF (IHDR .EQ. 1) THEN
         CALL OPEN (*95,IFILE,IZ(IBUF),0)
         CALL READ (*95,*95,IFILE,IZ,-2,0,N)
         CALL READ (*95,*10,IFILE,IZ,NZ,0,N)
         CALL MESAGE (-8,0,IFILE)
   10    KH = 105
         CALL N95TBL (KH,1,N,IZ)
      ELSE
         CALL GOPEN (IFILE,IZ(IBUF),0)
      ENDIF
      CALL N95TMB (KIND,NROW,NCOL,ICPX)
      NW = NROW
      IF (ICPX .EQ. 1) NW = 2*NROW
      ALLOCATE (COL(MAX(NW,1)))
      ITC  = 2
      IF (ICPX .EQ. 1) ITC = 4
      II   = 1
      JJ   = NROW
      INCR = 1
      DO 50 J = 1,NCOL
      CALL UNPACK (*30,IFILE,COL)
      GO TO 40
   30 COL(1:NW) = 0.0D0
   40 CALL N95TMC (KIND,J,COL)
   50 CONTINUE
      DEALLOCATE (COL)
      CALL CLOSE (IFILE,1)
      RETURN
   95 CALL MESAGE (-2,IFILE,0)
      RETURN
      END
C
C
      SUBROUTINE AETRWM (IFILE,KIND,IZ,IBUF)
C
C     HALO: THE OUTPUT MATRIX KIND FROM THE C SIDE TO IFILE, REAL DOUBLE
C     PRECISION, A COLUMN AT A TIME; NOTHING WHEN IFILE IS PURGED
C
      INTEGER         IFILE,KIND,IZ(1),IBUF,MCB(7),NROW,NCOL,IFORM,J,
     1                ITI,ITO,II,JJ,INCR
      DOUBLE PRECISION, ALLOCATABLE :: COL(:)
      COMMON /PACKX / ITI,ITO,II,JJ,INCR
      MCB(1) = IFILE
      CALL RDTRL (MCB)
      IF (MCB(1) .LE. 0) RETURN
      CALL N95TOS (KIND,NROW,NCOL,IFORM)
      IF (NROW.LE.0 .OR. NCOL.LE.0) RETURN
      ALLOCATE (COL(NROW))
      MCB(1) = IFILE
      MCB(2) = 0
      MCB(3) = NROW
      MCB(4) = IFORM
      MCB(5) = 2
      MCB(6) = 0
      MCB(7) = 0
      CALL GOPEN (IFILE,IZ(IBUF),1)
      ITI  = 2
      ITO  = 2
      II   = 1
      JJ   = NROW
      INCR = 1
      DO 10 J = 1,NCOL
      CALL N95TGC (KIND,J,COL)
      CALL PACK (COL,IFILE,MCB)
   10 CONTINUE
      CALL CLOSE (IFILE,1)
      CALL WRTTRL (MCB)
      DEALLOCATE (COL)
      RETURN
      END
