      SUBROUTINE AMPCZ (AJJ,DJH,QJH,NJ,NOH,ITOUT,IFORM,ISUCCS)
C
C     THE IN-CORE SOLVE OF THE DOUBLET LATTICE PORTION OF AMPC.
C
C     THE ORIGINAL PATH TRANSPOSES AJJ (TRANP1), DECOMPOSES THE
C     TRANSPOSE OUT OF CORE THROUGH GINO (CFACTR) AND SOLVES FOR THE
C     NOH COLUMNS OF DJH (CFBSOR), ONCE PER (MACH, K) PAIR. ON A MODEL
C     OF TWO THOUSAND BOXES THAT IS HOURS PER MACH, ALMOST ALL OF IT IN
C     THE DECOMPOSITION. HERE AJJ IS UNPACKED TRANSPOSED INTO OPEN CORE
C     AS COMPLEX DOUBLE PRECISION, FACTORED IN PLACE WITH PARTIAL
C     PIVOTING, THE RIGHT HAND SIDES ARE SOLVED AND PACKED TO QJH -
C     THE SAME QJH = (AJJ**T)**-1 * DJH, IN DOUBLE PRECISION.
C
C     AJJ     GINO FILE, NJ X NJ COMPLEX, CLOSED AND REWOUND
C     DJH     GINO FILE, NJ X NOH COMPLEX, CLOSED AND REWOUND
C     QJH     GINO FILE WRITTEN HERE, NJ X NOH, TYPE ITOUT, FORM IFORM
C     ISUCCS  1 WHEN QJH WAS WRITTEN; 0 WHEN THE MATRICES DO NOT FIT
C             IN OPEN CORE, A PIVOT VANISHES OR THE ENVIRONMENT HAS
C             N95_INCORE_AJJ=0, AND THE CALLER TAKES THE ORIGINAL PATH
C
      INTEGER          AJJ,DJH,QJH,NJ,NOH,ITOUT,IFORM,ISUCCS,SYSBUF
      COMMON /SYSTEM/  SYSBUF,NOUT
      COMMON /ZZZZZZ/  IZ(1)
      CHARACTER*8      ENV
C
      ISUCCS = 0
      ENV = ' '
      CALL GETENV ('N95_INCORE_AJJ',ENV)
      IF (ENV(1:1) .EQ. '0') RETURN
      IF (NJ .LE. 0 .OR. NOH .LE. 0) RETURN
C
C     OPEN CORE, IN SINGLE WORDS. A COMPLEX DOUBLE IS FOUR WORDS; EVERY
C     ARRAY STARTS ON AN ODD WORD SO THAT IT IS ALIGNED TO EIGHT BYTES.
C     THE GINO BUFFER SITS AT THE TOP AS EVERYWHERE ELSE.
C
      NZ    = KORSZ(IZ)
      IBUF1 = NZ - SYSBUF + 1
      IA    = 1
      IB    = IA + 4*NJ*NJ
      IC    = IB + 4*NJ*NOH
      IP    = IC + 4*NJ
      NEED  = IP + NJ + 1
      IF (NEED .GE. IBUF1 - SYSBUF) RETURN
      CALL AMPCZ1 (AJJ,DJH,QJH,NJ,NOH,ITOUT,IFORM,IZ(IA),IZ(IB),
     1             IZ(IC),IZ(IP),IZ(IBUF1),ISUCCS)
      RETURN
      END

      SUBROUTINE AMPCZ1 (AJJ,DJH,QJH,N,NOH,ITOUT,IFORM,AT,B,COL,IPIV,
     1                   BUF,ISUCCS)
C
C     THE WORK OF AMPCZ ON THE ARRAYS IT CARVED OUT OF OPEN CORE
C
      INTEGER          AJJ,DJH,QJH,N,NOH,ITOUT,IFORM,IPIV(N),BUF(1),
     1                 ISUCCS
      DOUBLE COMPLEX   AT(N,N),B(N,NOH),COL(N)
      INTEGER          MCB(7),ITC,II,JJ,INCR,ITC1,ITC2,II1,JJ1,INCR1
      COMMON /UNPAKX/  ITC,II,JJ,INCR
      COMMON /PACKX /  ITC1,ITC2,II1,JJ1,INCR1
      DOUBLE COMPLEX   ZERO
      INTEGER          I,J,IOK
C
      ZERO = (0.D0,0.D0)
C
C     AJJ, ONE COLUMN AT A TIME, INTO THE ROWS OF AT
C
      ITC  = 4
      II   = 1
      JJ   = N
      INCR = 1
      CALL GOPEN (AJJ,BUF,0)
      DO 30 J = 1,N
      CALL UNPACK (*10,AJJ,COL)
      GO TO 20
   10 DO 15 I = 1,N
   15 COL(I) = ZERO
   20 DO 25 I = 1,N
   25 AT(J,I) = COL(I)
   30 CONTINUE
      CALL CLOSE (AJJ,1)
C
C     DJH INTO B
C
      CALL GOPEN (DJH,BUF,0)
      DO 60 J = 1,NOH
      CALL UNPACK (*40,DJH,B(1,J))
      GO TO 60
   40 DO 45 I = 1,N
   45 B(I,J) = ZERO
   60 CONTINUE
      CALL CLOSE (DJH,1)
C
C     THE SOLVE, AT X = B IN PLACE OF B: AMPCZS, ONE OF TWO BUILDS OF IT
C     (MIS/AMPCZS/, CHOSEN BY CMAKE) - LAPACK'S ZGETRF + ZGETRS WHEN THE
C     BUILD LINKS A LAPACK (NASTRAN_LAPACK_LIBRARIES; THE LINUX BUILD
C     LINKS OPENBLAS), ELSE THE THREADED LU THAT WAS HERE. IOK 0 WHEN A
C     PIVOT VANISHES, AND THE CALLER TAKES THE ORIGINAL PATH.
C
      CALL AMPCZS (AT,B,N,NOH,IPIV,IOK)
      IF (IOK .EQ. 0) RETURN
C
C     QJH, PACKED FROM COMPLEX DOUBLE TO THE TYPE THE ORIGINAL PATH
C     WOULD HAVE WRITTEN, WITH THE TRAILER CFBSOR WOULD HAVE LEFT
C
      ITC1  = 4
      ITC2  = ITOUT
      II1   = 1
      JJ1   = N
      INCR1 = 1
      MCB(1) = QJH
      MCB(2) = 0
      MCB(3) = N
      MCB(4) = IFORM
      MCB(5) = ITOUT
      MCB(6) = 0
      MCB(7) = 0
      CALL GOPEN (QJH,BUF,1)
      DO 300 J = 1,NOH
  300 CALL PACK (B(1,J),QJH,MCB)
      CALL CLOSE (QJH,1)
      CALL WRTTRL (MCB)
      ISUCCS = 1
      RETURN
      END
