      SUBROUTINE AMPCZ (AJJ,DJH,QJH,NJ,NOH,ITOUT,IFORM,ISUCCS)
C
C     THE IN-CORE SOLVE OF THE DOUBLET LATTICE PORTION OF AMPC.
C
C     THE ORIGINAL PATH TRANSPOSES AJJ (TRANP1), DECOMPOSES THE
C     TRANSPOSE OUT OF CORE THROUGH GINO (CFACTR) AND SOLVES FOR THE
C     NOH COLUMNS OF DJH (CFBSOR), ONCE PER (MACH, K) PAIR. ON A MODEL
C     OF TWO THOUSAND BOXES THAT IS HOURS PER MACH, ALMOST ALL OF IT IN
C     THE DECOMPOSITION. HERE AJJ IS UNPACKED TRANSPOSED INTO OPEN CORE
C     AS COMPLEX DOUBLE PRECISION, FACTORED IN PLACE WITH PARTIAL
C     PIVOTING, THE RIGHT HAND SIDES ARE SOLVED AND PACKED TO QJH -
C     THE SAME QJH = (AJJ**T)**-1 * DJH, IN DOUBLE PRECISION.
C
C     AJJ     GINO FILE, NJ X NJ COMPLEX, CLOSED AND REWOUND
C     DJH     GINO FILE, NJ X NOH COMPLEX, CLOSED AND REWOUND
C     QJH     GINO FILE WRITTEN HERE, NJ X NOH, TYPE ITOUT, FORM IFORM
C     ISUCCS  1 WHEN QJH WAS WRITTEN; 0 WHEN THE MATRICES DO NOT FIT
C             IN OPEN CORE, A PIVOT VANISHES OR THE ENVIRONMENT HAS
C             N95_INCORE_AJJ=0, AND THE CALLER TAKES THE ORIGINAL PATH
C
      INTEGER          AJJ,DJH,QJH,NJ,NOH,ITOUT,IFORM,ISUCCS,SYSBUF
      COMMON /SYSTEM/  SYSBUF,NOUT
      COMMON /ZZZZZZ/  IZ(1)
      CHARACTER*8      ENV
C
      ISUCCS = 0
      ENV = ' '
      CALL GETENV ('N95_INCORE_AJJ',ENV)
      IF (ENV(1:1) .EQ. '0') RETURN
      IF (NJ .LE. 0 .OR. NOH .LE. 0) RETURN
C
C     OPEN CORE, IN SINGLE WORDS. A COMPLEX DOUBLE IS FOUR WORDS; EVERY
C     ARRAY STARTS ON AN ODD WORD SO THAT IT IS ALIGNED TO EIGHT BYTES.
C     THE GINO BUFFER SITS AT THE TOP AS EVERYWHERE ELSE.
C
      NZ    = KORSZ(IZ)
      IBUF1 = NZ - SYSBUF + 1
      IA    = 1
      IB    = IA + 4*NJ*NJ
      IC    = IB + 4*NJ*NOH
      IP    = IC + 4*NJ
      NEED  = IP + NJ + 1
      IF (NEED .GE. IBUF1 - SYSBUF) RETURN
      CALL AMPCZ1 (AJJ,DJH,QJH,NJ,NOH,ITOUT,IFORM,IZ(IA),IZ(IB),
     1             IZ(IC),IZ(IP),IZ(IBUF1),ISUCCS)
      RETURN
      END

      SUBROUTINE AMPCZ1 (AJJ,DJH,QJH,N,NOH,ITOUT,IFORM,AT,B,COL,IPIV,
     1                   BUF,ISUCCS)
C
C     THE WORK OF AMPCZ ON THE ARRAYS IT CARVED OUT OF OPEN CORE
C
      INTEGER          AJJ,DJH,QJH,N,NOH,ITOUT,IFORM,IPIV(N),BUF(1),
     1                 ISUCCS
      DOUBLE COMPLEX   AT(N,N),B(N,NOH),COL(N)
      INTEGER          MCB(7),ITC,II,JJ,INCR,ITC1,ITC2,II1,JJ1,INCR1
      COMMON /UNPAKX/  ITC,II,JJ,INCR
      COMMON /PACKX /  ITC1,ITC2,II1,JJ1,INCR1
      DOUBLE PRECISION AMAX,T
      DOUBLE COMPLEX   R,S,ZERO
      INTEGER          I,J,K,IPK
C
      ZERO = (0.D0,0.D0)
C
C     AJJ, ONE COLUMN AT A TIME, INTO THE ROWS OF AT
C
      ITC  = 4
      II   = 1
      JJ   = N
      INCR = 1
      CALL GOPEN (AJJ,BUF,0)
      DO 30 J = 1,N
      CALL UNPACK (*10,AJJ,COL)
      GO TO 20
   10 DO 15 I = 1,N
   15 COL(I) = ZERO
   20 DO 25 I = 1,N
   25 AT(J,I) = COL(I)
   30 CONTINUE
      CALL CLOSE (AJJ,1)
C
C     DJH INTO B
C
      CALL GOPEN (DJH,BUF,0)
      DO 60 J = 1,NOH
      CALL UNPACK (*40,DJH,B(1,J))
      GO TO 60
   40 DO 45 I = 1,N
   45 B(I,J) = ZERO
   60 CONTINUE
      CALL CLOSE (DJH,1)
C
C     LU OF AT IN PLACE, PARTIAL PIVOTING BY ROWS: P*AT = L*U WITH
C     L UNIT LOWER TRIANGULAR BELOW THE DIAGONAL AND U ON AND ABOVE.
C     THE PIVOT ROW IS SWAPPED ACROSS ALL N COLUMNS SO THAT THE
C     INTERCHANGES CAN BE APPLIED TO A RIGHT HAND SIDE IN ORDER.
C     THE TRAILING UPDATE, WHERE THE TIME GOES, IS THREADED OVER ITS
C     COLUMNS WHEN THE BUILD HAS OPENMP.
C
      DO 200 K = 1,N
      IPK  = K
      AMAX = ABS(DBLE(AT(K,K))) + ABS(DIMAG(AT(K,K)))
      DO 110 I = K+1,N
      T = ABS(DBLE(AT(I,K))) + ABS(DIMAG(AT(I,K)))
      IF (T .LE. AMAX) GO TO 110
      AMAX = T
      IPK  = I
  110 CONTINUE
      IPIV(K) = IPK
      IF (AMAX .EQ. 0.D0) RETURN
      IF (IPK .EQ. K) GO TO 130
      DO 120 J = 1,N
      S = AT(K,J)
      AT(K,J)   = AT(IPK,J)
      AT(IPK,J) = S
  120 CONTINUE
  130 IF (K .EQ. N) GO TO 200
      R = (1.D0,0.D0)/AT(K,K)
      DO 140 I = K+1,N
  140 AT(I,K) = AT(I,K)*R
!$OMP PARALLEL DO PRIVATE(I,S) SCHEDULE(STATIC)
      DO 160 J = K+1,N
      S = AT(K,J)
      IF (S .NE. ZERO) THEN
         DO 150 I = K+1,N
  150    AT(I,J) = AT(I,J) - AT(I,K)*S
      END IF
  160 CONTINUE
!$OMP END PARALLEL DO
  200 CONTINUE
C
C     THE ROW INTERCHANGES ON B, THEN L*Y = P*B AND U*X = Y, A COLUMN
C     OF B AT A TIME (THE COLUMNS ARE INDEPENDENT, SO THREADED)
C
      DO 220 K = 1,N
      IPK = IPIV(K)
      IF (IPK .EQ. K) GO TO 220
      DO 210 J = 1,NOH
      S = B(K,J)
      B(K,J)   = B(IPK,J)
      B(IPK,J) = S
  210 CONTINUE
  220 CONTINUE
!$OMP PARALLEL DO PRIVATE(I,K,S) SCHEDULE(STATIC)
      DO 260 J = 1,NOH
      DO 240 K = 1,N
      S = B(K,J)
      IF (S .NE. ZERO) THEN
         DO 230 I = K+1,N
  230    B(I,J) = B(I,J) - AT(I,K)*S
      END IF
  240 CONTINUE
      DO 255 K = N,1,-1
      B(K,J) = B(K,J)/AT(K,K)
      S = B(K,J)
      DO 250 I = 1,K-1
  250 B(I,J) = B(I,J) - AT(I,K)*S
  255 CONTINUE
  260 CONTINUE
!$OMP END PARALLEL DO
C
C     QJH, PACKED FROM COMPLEX DOUBLE TO THE TYPE THE ORIGINAL PATH
C     WOULD HAVE WRITTEN, WITH THE TRAILER CFBSOR WOULD HAVE LEFT
C
      ITC1  = 4
      ITC2  = ITOUT
      II1   = 1
      JJ1   = N
      INCR1 = 1
      MCB(1) = QJH
      MCB(2) = 0
      MCB(3) = N
      MCB(4) = IFORM
      MCB(5) = ITOUT
      MCB(6) = 0
      MCB(7) = 0
      CALL GOPEN (QJH,BUF,1)
      DO 300 J = 1,NOH
  300 CALL PACK (B(1,J),QJH,MCB)
      CALL CLOSE (QJH,1)
      CALL WRTTRL (MCB)
      ISUCCS = 1
      RETURN
      END
