      MODULE AMPKM
C
C     HALO: ONE SLOT OF AMPK'S PIPELINE - WHAT ONE (MACH, K) PAIR HOLDS
C     BETWEEN BEING READ, SOLVED AND WRITTEN.
C
C     AS      AJJ AS READ, WHEN AJJL IS COMPLEX SINGLE (ITS OWN TYPE)
C     AT      AJJ TRANSPOSED, COMPLEX DOUBLE - THE MATRIX AMPCZ FACTORS
C     B       DJH, THEN QJH IN ITS PLACE
C     KP..KV  THE PAIR'S COLUMNS OF SKJ, COMPRESSED: COLUMN J'S TERMS
C             ARE KR(KP(J)..KP(J+1)-1) (ROWS) AND KV (VALUES)
C     QK, QI  QKH = SKJ QJH AND QIH = GKI(T) QKH
C
      TYPE AMPKS
         INTEGER                     :: IP = 0, IOK = 0
         REAL                        :: XK = 0.0
         COMPLEX,        ALLOCATABLE :: AS(:,:)
         DOUBLE COMPLEX, ALLOCATABLE :: AT(:,:), B(:,:)
         DOUBLE COMPLEX, ALLOCATABLE :: QK(:,:), QI(:,:), KV(:)
         INTEGER,        ALLOCATABLE :: IPIV(:), KP(:), KR(:)
      END TYPE
      END MODULE

      SUBROUTINE AMPK (AJJL,SKJ,DJH1,DJH2,GKI,PAIRS,IMAX,IDONE,NLEFT)
C
C     HALO: AMP'S LOOP ON (MACH, K) PAIRS IN CORE, THE PAIRS SOLVED SIDE
C     BY SIDE.
C
C     FOR EACH PAIR AMP CALLS AMPC AND AMPD, WHICH GO THROUGH GINO FOR
C     EVERY STEP: DJH = DJH1 + I*K*DJH2 (SSG2C), A COPY OF THE PAIR'S
C     AJJ (AMPC1), THE IN-CORE SOLVE QJH = (AJJ**T)**-1 DJH (AMPCZ),
C     A COPY OF THE PAIR'S SKJ (CYCT2B), QKH = SKJ QJH AND QIH = GKI(T)
C     QKH (MPYAD, METHODS 21 AND 10), AND COPIES OF QKH TO QJHL AND QIH
C     TO QHHL - ALL SERIAL, ALL AT -O0, AND ON A LARGE MODEL AMP'S WALL
C     CLOCK: ON THE MONARCH (2,282 BOXES, 120 MODES) 0.35 S A PAIR, 17
C     S FOR THE MACH WITH 48 K, 41 S WHEN THE OTHER MACHS' CHILDREN
C     SHARE THE MACHINE.
C
C     HERE THE PAIRS ARE A PIPELINE OF OPENMP TASKS. ONE READ TASK PER
C     PAIR TAKES ITS AJJ AND SKJ OFF AJJL AND SKJ (KEPT OPEN, READ IN
C     ORDER), ONE COMPUTE TASK DOES EVERYTHING ELSE IN CORE, AND ONE
C     WRITE TASK PACKS ITS QKH TO QJHL AND ITS QIH TO QHHL. THE READS
C     AND WRITES - EVERY GINO CALL - ARE CHAINED ON ONE DEPENDENCE
C     (ITOK), IN PAIR ORDER, SO GINO SEES ONE CALLER AT A TIME AND THE
C     FILES THE SAME SEQUENCE OF COLUMNS AS BEFORE; THE COMPUTE TASKS
C     RUN AS MANY AT A TIME AS THERE ARE SLOTS (NS). EACH SOLVE IS
C     SINGLE-THREADED (LAPACK INSIDE AN OPENMP REGION RUNS ON ONE
C     THREAD; OPENBLAS'S ZGETRF GIVES THE SAME BITS ON 1 THREAD AS ON
C     32).
C
C     THE ARITHMETIC IS THE SERIAL PATH'S, OPERATION FOR OPERATION:
C       DJH  SADD'S TWO MULTIPLY-ADDS PER ELEMENT, WITH ITS MULTIPLIERS
C            (1,0) AND (0,K), IN DOUBLE PRECISION (AMPKC, 20)
C       QJH  THE SAME AMPCZS SOLVE, ON THE SAME AJJ(T) AND DJH (AMPCZR)
C       QKH  MMA214'S "A NOT TRANSPOSED": QKH(K,H) SUMMED OVER SKJ'S
C            COLUMNS J IN ORDER, SKJ(K,J)*QJH(J,H) EACH
C       QIH  MMA104'S "A TRANSPOSED": QIH(I,H) SUMMED OVER K IN ORDER,
C            GKI(K,I)*QKH(K,H) EACH, GKI AS COMPLEX WITH ZERO IMAGINARY
C     THE SERIAL PATH SKIPS THE TERMS WHOSE FACTORS ARE NOT STORED
C     (ZERO); THIS KEEPS THEM. A PRODUCT WITH A ZERO FACTOR IS A ZERO OF
C     EITHER SIGN, AND ADDING ONE TO A SUM THAT STARTED AT +0 CHANGES
C     NOTHING (THE SUM IS NONZERO, OR +0: -0 NEEDS BOTH TERMS -0), SO
C     THE SUMS ARE THE SAME TO THE BIT. THE COMPLEX DOUBLE VALUES THE
C     SERIAL PATH PACKS AND UNPACKS BETWEEN STEPS COME BACK UNCHANGED.
C
C     TAKEN WHEN: ONE AERODYNAMIC GROUP OF DOUBLET LATTICE BOXES (THE
C     IN-CORE CASE OF AMPC), NO PAIR TAKEN FROM AN OLD QHHL, DOUBLE
C     PRECISION (IPREC 2, SO DJH, QJH, QKH AND QHH ARE COMPLEX DOUBLE),
C     AT LEAST ONE OF DJH1 AND DJH2 IN DOUBLE PRECISION (SADD WORKS IN
C     DOUBLE THEN), AND ROOM IN OPEN CORE FOR THREE GINO BUFFERS. ELSE
C     IDONE = 0 AND AMP RUNS ITS OWN LOOP, AS IT DOES WITH
C     N95_AMP_PIPE=0 OR N95_INCORE_AJJ=0 IN THE ENVIRONMENT.
C
C     N95_AMP_SLOTS  THE NUMBER OF PAIRS IN CORE AT ONCE (DEFAULT: THE
C                    THREADS + 1, AT MOST 16, AND WHAT N95_AMP_MB -
C                    DEFAULT 4096 - HOLDS; A SLOT IS ABOUT 26 NJ**2
C                    BYTES, 140 MB ON THE MONARCH)
C
C     IDONE  1 WHEN THE PAIRS WERE DONE HERE (NLEFT OF THEM LEFT OVER
C            WHEN THE TIME RAN OUT, FOR AMP'S MESSAGE 45), 0 WHEN NOT
C
      USE AMPKM
      INTEGER          AJJL,SKJ,DJH1,DJH2,GKI,PAIRS,IMAX,IDONE,NLEFT
      INTEGER          SYSBUF,AJJCOL,QHHCOL,NAME(2),MCB(7),PRC(4)
      REAL             XK
      COMMON /SYSTEM/  SYSBUF,NOUT,SKP(52),IPREC
      COMMON /AMPCOM/  NCOL,NSUB,XM,XK,AJJCOL,QHHCOL,NGP,NGPD(2,30),
     1                 MCBQHH(7),MCBQJH(7),NOH,IDJH,MCBRJH(7)
      COMMON /AMPHLO/  NEXTC,NEXTS
      COMMON /ZZZZZZ/  IZ(1)
      COMMON /UNPAKX/  ITC,II,JJ,INCR
      TYPE(AMPKS),     ALLOCATABLE :: SL(:)
      DOUBLE COMPLEX,  ALLOCATABLE :: D1(:,:),D2(:,:),GK(:,:),COL(:)
      INTEGER,         ALLOCATABLE :: IREC(:,:)
      INTEGER          ITOK,IDEP(64),NS,NT,IP,IS,IAJJT,NJ,NK,ISOLV,
     1                 NXA,NXS,ISTOP,NDONE,IBA,IBS,IBW,IERR,IOS,MB,
     2                 ITS,ITL
      REAL             XREC(4)
      INTEGER          JREC(4)
      EQUIVALENCE      (XREC(1),JREC(1))
      CHARACTER*16     ENV
      CHARACTER        UFM*23,UWM*25,UIM*29,SFM*25
      COMMON /XMSSG /  UFM,UWM,UIM,SFM
!$    INTEGER          OMP_GET_MAX_THREADS
      DATA    NAME  /  4HAMPK,4H     /
      DATA    PRC   /  1,2,1,2 /
C
      IDONE = 0
      NLEFT = 0
      ENV = ' '
      CALL GETENV ('N95_AMP_PIPE',ENV)
      IF (ENV(1:1) .EQ. '0') RETURN
      ENV = ' '
      CALL GETENV ('N95_INCORE_AJJ',ENV)
      IF (ENV(1:1) .EQ. '0') RETURN
      IF (IMAX .LE. 0 .OR. NOH .LE. 0) RETURN
      IF (IPREC .NE. 2) RETURN
      IF (NGP .NE. 1) RETURN
      IF (NGPD(1,1).NE.1 .AND. NGPD(1,1).NE.2) RETURN
      IF (MCBQHH(1).LE.0 .OR. MCBQHH(5).NE.4) RETURN
      IF (MCBQJH(1).GT.0 .AND. MCBQJH(5).NE.4) RETURN
      NJ = NGPD(2,1)
      IF (NJ .NE. NCOL) RETURN
C
C     THE MATRICES' SHAPES AND TYPES
C
      MCB(1) = AJJL
      CALL RDTRL (MCB)
      IAJJT = MCB(5)
      IF (MCB(3) .NE. NJ) RETURN
      IF (IAJJT.NE.3 .AND. IAJJT.NE.4) RETURN
      MCB(1) = SKJ
      CALL RDTRL (MCB)
      NK = MCB(3)
      IF (MCB(1).LE.0 .OR. NK.LE.0) RETURN
      IF (MCB(5).LT.1 .OR. MCB(5).GT.4) RETURN
      MCB(1) = GKI
      CALL RDTRL (MCB)
      IF (MCB(2).NE.NOH .OR. MCB(3).NE.NK) RETURN
      IF (MCB(5).LT.1 .OR. MCB(5).GT.4) RETURN
      MCB(1) = DJH1
      CALL RDTRL (MCB)
      IF (MCB(2).NE.NOH .OR. MCB(3).NE.NJ) RETURN
      IF (MCB(5).LT.1 .OR. MCB(5).GT.4) RETURN
      IT1 = MCB(5)
      MCB(1) = DJH2
      CALL RDTRL (MCB)
      IF (MCB(2).NE.NOH .OR. MCB(3).NE.NJ) RETURN
      IF (MCB(5).LT.1 .OR. MCB(5).GT.4) RETURN
      IF (PRC(IT1)+PRC(MCB(5)) .LE. 2) RETURN
C
C     THREE GINO BUFFERS AT THE TOP OF OPEN CORE: AJJL, SKJ, AND ONE FOR
C     THE OTHER FILES IN TURN (THE PAIRS, DJH1, DJH2, GKI, QJHL, QHHL)
C
      IBA = KORSZ(IZ) - SYSBUF + 1
      IBS = IBA - SYSBUF
      IBW = IBS - SYSBUF
      IF (IBW .LE. SYSBUF) RETURN
C
C     THE PAIRS (AMPA'S INDEX: MACH, K, AJJCOL, QHHCOL); ANY TAKEN FROM
C     AN OLD QHHL LEAVES THEM ALL TO AMP'S OWN LOOP
C
      ALLOCATE (IREC(4,IMAX))
      CALL GOPEN (PAIRS,IZ(IBW),0)
      DO 10 IP = 1,IMAX
      CALL FREAD (PAIRS,IREC(1,IP),4,1)
   10 CONTINUE
      CALL CLOSE (PAIRS,1)
      DO 15 IP = 1,IMAX
      IF (IREC(4,IP) .NE. 0) RETURN
   15 CONTINUE
C
C     THE SOLVE (N95_AJJ_SOLVE=BUILTIN AS IN AMPCZS), THE THREADS, THE
C     SLOTS
C
      ISOLV = 0
      ENV = ' '
      CALL GETENV ('N95_AJJ_SOLVE',ENV)
      IF (ENV(1:1).EQ.'B' .OR. ENV(1:1).EQ.'b') ISOLV = 1
      NT = 1
!$    NT = OMP_GET_MAX_THREADS()
      MB = 4096
      ENV = ' '
      CALL GETENV ('N95_AMP_MB',ENV)
      IF (ENV .NE. ' ') READ (ENV,*,IOSTAT=IOS) MB
      IF (MB .LE. 0) MB = 4096
      NS = MIN(IMAX,NT+1,16)
      NS = MIN(NS,MAX(1,INT(DBLE(MB)*1.0D6/(26.0D0*DBLE(NJ)**2))))
      ENV = ' '
      CALL GETENV ('N95_AMP_SLOTS',ENV)
      IF (ENV .NE. ' ') READ (ENV,*,IOSTAT=IOS) NS
      NS = MAX(1,MIN(NS,IMAX,64))
C
C     DJH1, DJH2 AND GKI, COMPLEX DOUBLE, FOR THE WHOLE LOOP
C
      ALLOCATE (D1(NJ,NOH),D2(NJ,NOH),GK(NK,NOH),COL(MAX(NJ,NK)))
      CALL AMPKM1 (DJH1,D1,NJ,NOH,IZ(IBW))
      CALL AMPKM1 (DJH2,D2,NJ,NOH,IZ(IBW))
      CALL AMPKM1 (GKI, GK,NK,NOH,IZ(IBW))
      ALLOCATE (SL(NS))
      DO 20 IS = 1,NS
      IF (IAJJT .EQ. 3) ALLOCATE (SL(IS)%AS(NJ,NJ))
      ALLOCATE (SL(IS)%AT(NJ,NJ),SL(IS)%B(NJ,NOH),SL(IS)%IPIV(NJ),
     1          SL(IS)%QK(NK,NOH),SL(IS)%QI(NOH,NOH),SL(IS)%KP(NJ+1),
     2          SL(IS)%KR(4*NJ),SL(IS)%KV(4*NJ))
   20 CONTINUE
C
C     THE PIPELINE. AJJL AND SKJ STAY OPEN AND ARE READ FORWARD; NXA
C     AND NXS ARE THE COLUMNS THEY STAND AT.
C
      CALL GOPEN (AJJL,IZ(IBA),0)
      CALL GOPEN (SKJ, IZ(IBS),0)
      NXA   = 1
      NXS   = 1
      ISTOP = 0
      NDONE = 0
      IERR  = 0
      ITL   = 0
      CALL KLOCK (ITS)
!$OMP PARALLEL NUM_THREADS(NT) DEFAULT(SHARED)
!$OMP SINGLE
      DO 40 IP = 1,MIN(NS,IMAX)
      IS = IP
!$OMP TASK FIRSTPRIVATE(IP,IS) DEPEND(INOUT:ITOK,IDEP(IS))
      CALL AMPKR (SL(IS),IP,IREC(1,IP),AJJL,SKJ,IAJJT,NJ,NK,NXA,NXS,
     1            IZ(IBA),IZ(IBS),COL,ISTOP,ITS,ITL)
!$OMP END TASK
!$OMP TASK FIRSTPRIVATE(IS) DEPEND(INOUT:IDEP(IS))
      CALL AMPKC (SL(IS),D1,D2,GK,NJ,NK,NOH,IAJJT,ISOLV)
!$OMP END TASK
   40 CONTINUE
      DO 50 IP = 1,IMAX
      IS = MOD(IP-1,NS) + 1
!$OMP TASK FIRSTPRIVATE(IP,IS) DEPEND(INOUT:ITOK,IDEP(IS))
      CALL AMPKW (SL(IS),IP,NK,NOH,IZ(IBW),NDONE,IERR)
!$OMP END TASK
      IF (IP+NS .GT. IMAX) GO TO 50
      JP = IP + NS
!$OMP TASK FIRSTPRIVATE(JP,IS) DEPEND(INOUT:ITOK,IDEP(IS))
      CALL AMPKR (SL(IS),JP,IREC(1,JP),AJJL,SKJ,IAJJT,NJ,NK,NXA,NXS,
     1            IZ(IBA),IZ(IBS),COL,ISTOP,ITS,ITL)
!$OMP END TASK
!$OMP TASK FIRSTPRIVATE(IS) DEPEND(INOUT:IDEP(IS))
      CALL AMPKC (SL(IS),D1,D2,GK,NJ,NK,NOH,IAJJT,ISOLV)
!$OMP END TASK
   50 CONTINUE
!$OMP END SINGLE
!$OMP END PARALLEL
      CALL CLOSE (AJJL,1)
      CALL CLOSE (SKJ, 1)
C
C     A PIVOT VANISHED: THE SERIAL PATH WOULD HAVE TAKEN THE OUT OF CORE
C     DECOMPOSITION FOR THAT PAIR AND STOPPED THERE ON THE SAME SINGULAR
C     MATRIX
C
      IF (IERR .NE. 0) GO TO 900
C
C     AS AMP'S LOOP LEAVES THEM: THE LAST PAIR IN /AMPCOM/, THE FILES
C     NOT WHERE AMPF EXPECTS THEM (IT REWINDS), QJHL'S ROWS THE K-SET
C
      IF (NDONE .EQ. 0) GO TO 60
      JREC(1) = IREC(1,NDONE)
      JREC(2) = IREC(2,NDONE)
      XM      = XREC(1)
      XK      = XREC(2)
      AJJCOL  = IREC(3,NDONE)
      QHHCOL  = 0
   60 CONTINUE
      NEXTC   = 0
      NEXTS   = 0
      MCBQJH(3) = NK
      NLEFT = IMAX - NDONE
      IDONE = 1
      RETURN
C
  900 WRITE  (NOUT,910) SFM,IERR
  910 FORMAT (A25,' 9150, THE IN-CORE SOLVE OF THE DOUBLET LATTICE ',
     1        'MATRIX FOUND A ZERO PIVOT', /5X,'AT (MACH, K) PAIR',I5,
     2        ' OF THE AERODYNAMIC LIST - THE MATRIX IS SINGULAR.')
      CALL MESAGE (-61,0,NAME)
      RETURN
      END

      SUBROUTINE AMPKM1 (FILE,D,NR,NC,BUF)
C
C     HALO: A WHOLE MATRIX OFF GINO INTO D, COMPLEX DOUBLE, AS MPYAD AND
C     SADD SEE IT (UNPACK CONVERTS EXACTLY; A TERM NOT STORED IS +0)
C
      INTEGER          FILE,NR,NC,BUF(1)
      DOUBLE COMPLEX   D(NR,NC)
      COMMON /UNPAKX/  ITC,II,JJ,INCR
      CALL GOPEN (FILE,BUF,0)
      DO 20 J = 1,NC
      ITC  = 4
      II   = 1
      JJ   = NR
      INCR = 1
      CALL UNPACK (*10,FILE,D(1,J))
      GO TO 20
   10 DO 15 I = 1,NR
   15 D(I,J) = (0.0D0,0.0D0)
   20 CONTINUE
      CALL CLOSE (FILE,1)
      RETURN
      END

      SUBROUTINE AMPKR (S,IP,IREC,AJJL,SKJ,IAJJT,NJ,NK,NXA,NXS,BUFA,
     1                  BUFS,COL,ISTOP,ITS,ITL)
C
C     HALO: AMPK'S READ OF PAIR IP INTO SLOT S - ITS AJJ COLUMNS OFF
C     AJJL AND ITS SKJ COLUMNS OFF SKJ, BOTH STARTING AT THE PAIR'S
C     AJJCOL, AS AMPC AND AMPD POSITION THEM. RUNS UNDER AMPK'S GINO
C     DEPENDENCE, SO IT IS THE ONLY GINO CALLER WHILE IT RUNS. WHEN THE
C     TIME IS UP (AMP'S OWN TEST, 1.1 TIMES THE LONGEST PAIR SO FAR
C     AGAINST THE TIME TO GO) IT READS NOTHING AND THE PAIRS FROM HERE
C     ON ARE LEFT.
C
      USE AMPKM
      TYPE(AMPKS)      S
      INTEGER          IP,IREC(4),AJJL,SKJ,IAJJT,NJ,NK,NXA,NXS,
     1                 BUFA(1),BUFS(1),ISTOP,ITS,ITL,JCOL,NNZ,ITF,ITMTO
      DOUBLE COMPLEX   COL(1),V
      INTEGER,         ALLOCATABLE :: KRN(:)
      DOUBLE COMPLEX,  ALLOCATABLE :: KVN(:)
      REAL             XREC(4)
      INTEGER          JREC(4)
      EQUIVALENCE      (XREC(1),JREC(1))
      COMMON /UNPAKX/  ITC,II,JJ,INCR
      INTEGER          NAME(2)
      DATA    NAME  /  4HAMPK,4HR    /
C
      S%IP  = IP
      S%IOK = 0
      IF (ISTOP .NE. 0) RETURN
      IF (IP .EQ. 1) GO TO 5
      CALL KLOCK (ITF)
      CALL TMTOGO (ITMTO)
      ITL = MAX0((ITF-ITS)/(IP-1),1,ITL)
      IF (1.1*ITL .LT. ITMTO) GO TO 5
      ISTOP = IP
      RETURN
    5 JREC(1) = IREC(1)
      JREC(2) = IREC(2)
      S%XK = XREC(2)
      JCOL = IREC(3)
C
C     AJJL TO COLUMN JCOL (FORWARD, OR FROM THE START)
C
      IF (JCOL .GE. NXA) GO TO 10
      CALL CLOSE (AJJL,1)
      CALL GOPEN (AJJL,BUFA,0)
      NXA = 1
   10 IF (NXA .GE. JCOL) GO TO 20
      CALL FWDREC (*900,AJJL)
      NXA = NXA + 1
      GO TO 10
C
C     THE PAIR'S NJ COLUMNS: AS THEY ARE STORED WHEN COMPLEX SINGLE
C     (INTO AS; AMPKC WIDENS AND TRANSPOSES), ELSE STRAIGHT INTO THE
C     COLUMNS OF AT (AMPKC TRANSPOSES IN PLACE)
C
   20 DO 40 J = 1,NJ
      ITC  = IAJJT
      II   = 1
      JJ   = NJ
      INCR = 1
      IF (IAJJT .EQ. 3) CALL UNPACK (*30,AJJL,S%AS(1,J))
      IF (IAJJT .EQ. 4) CALL UNPACK (*35,AJJL,S%AT(1,J))
      GO TO 40
   30 DO 32 I = 1,NJ
   32 S%AS(I,J) = (0.0,0.0)
      GO TO 40
   35 DO 37 I = 1,NJ
   37 S%AT(I,J) = (0.0D0,0.0D0)
   40 CONTINUE
      NXA = NXA + NJ
C
C     SKJ TO COLUMN JCOL, THEN ITS NJ COLUMNS' NONZERO TERMS
C
      IF (JCOL .GE. NXS) GO TO 50
      CALL CLOSE (SKJ,1)
      CALL GOPEN (SKJ,BUFS,0)
      NXS = 1
   50 IF (JCOL .GT. NXS) CALL SKPREC (SKJ,JCOL-NXS)
      NXS = JCOL
      NNZ = 0
      S%KP(1) = 1
      DO 80 J = 1,NJ
      ITC  = 4
      II   = 0
      JJ   = 0
      INCR = 1
      CALL UNPACK (*75,SKJ,COL)
      DO 70 K = II,JJ
      V = COL(K-II+1)
      IF (DBLE(V).EQ.0.0D0 .AND. DIMAG(V).EQ.0.0D0) GO TO 70
      IF (NNZ .LT. SIZE(S%KR)) GO TO 65
      ALLOCATE (KRN(2*SIZE(S%KR)),KVN(2*SIZE(S%KR)))
      KRN(1:NNZ) = S%KR(1:NNZ)
      KVN(1:NNZ) = S%KV(1:NNZ)
      CALL MOVE_ALLOC (KRN,S%KR)
      CALL MOVE_ALLOC (KVN,S%KV)
   65 NNZ = NNZ + 1
      S%KR(NNZ) = K
      S%KV(NNZ) = V
   70 CONTINUE
   75 S%KP(J+1) = NNZ + 1
   80 CONTINUE
      NXS = NXS + NJ
      S%IOK = 1
      RETURN
C
  900 CALL MESAGE (-2,AJJL,NAME)
      RETURN
      END

      SUBROUTINE AMPKC (S,D1,D2,GK,NJ,NK,NOH,IAJJT,ISOLV)
C
C     HALO: AMPK'S COMPUTE TASK FOR THE PAIR IN SLOT S - EVERYTHING
C     BETWEEN READING ITS AJJ AND SKJ AND WRITING ITS QKH AND QIH, WITH
C     THE SERIAL PATH'S ARITHMETIC (AMPK SAYS WHICH, AND WHY THE BITS
C     ARE THE SAME). NO GINO.
C
      USE AMPKM
      TYPE(AMPKS)      S
      INTEGER          NJ,NK,NOH,IAJJT,ISOLV,I,J,K,H,I0,J0,IE,JE,N
      DOUBLE COMPLEX   D1(NJ,NOH),D2(NJ,NOH),GK(NK,NOH),Q,ACC,T
      DOUBLE PRECISION AR,AI,BR,BI,ZR,ZI,A1R,A1I,A2R,A2I
      PARAMETER       (NB = 32)
C
C     S%IOK: 1 READ, 2 SOLVED, -1 A ZERO PIVOT, 0 NOTHING READ
      IF (S%IOK .NE. 1) RETURN
C
C     AT = AJJ(T), COMPLEX DOUBLE, AS AMPCZ1 STORES IT: WIDENED (EXACT)
C     AND TRANSPOSED FROM AS, OR TRANSPOSED IN PLACE. IN TILES.
C
      IF (IAJJT .NE. 3) GO TO 12
      DO 10 J0 = 1,NJ,NB
      JE = MIN(J0+NB-1,NJ)
      DO 10 I0 = 1,NJ,NB
      IE = MIN(I0+NB-1,NJ)
      DO 8 J = J0,JE
      DO 8 I = I0,IE
      S%AT(J,I) = DCMPLX(REAL(S%AS(I,J)),AIMAG(S%AS(I,J)))
    8 CONTINUE
   10 CONTINUE
      GO TO 18
   12 DO 16 J0 = 1,NJ,NB
      JE = MIN(J0+NB-1,NJ)
      DO 16 I0 = J0,NJ,NB
      IE = MIN(I0+NB-1,NJ)
      DO 14 J = J0,JE
      DO 14 I = MAX(I0,J+1),IE
      T = S%AT(I,J)
      S%AT(I,J) = S%AT(J,I)
      S%AT(J,I) = T
   14 CONTINUE
   16 CONTINUE
C
C     DJH = DJH1 + I*K*DJH2: SADD'S LOOP 450 FOR ITS TWO MATRICES, WITH
C     SSG2C'S MULTIPLIERS (1,0) AND (0,K) IN DOUBLE PRECISION
C
   18 A1R = 1.0D0
      A1I = 0.0D0
      A2R = 0.0D0
      A2I = S%XK
      DO 20 H = 1,NOH
      DO 20 I = 1,NJ
      AR = DBLE(D1(I,H))
      AI = DIMAG(D1(I,H))
      BR = DBLE(D2(I,H))
      BI = DIMAG(D2(I,H))
      ZR = (0.0D0 + A1R*AR) - A1I*AI
      ZI = (0.0D0 + A1R*AI) + A1I*AR
      ZR = (ZR + A2R*BR) - A2I*BI
      ZI = (ZI + A2R*BI) + A2I*BR
      S%B(I,H) = DCMPLX(ZR,ZI)
   20 CONTINUE
C
C     QJH = (AJJ**T)**-1 DJH, IN PLACE OF DJH
C
      CALL AMPCZR (S%AT,S%B,NJ,NOH,S%IPIV,IOK,ISOLV)
      S%IOK = -1
      IF (IOK .EQ. 0) RETURN
C
C     QKH = SKJ QJH: EACH QKH(K,H) A SUM OVER SKJ'S COLUMNS J IN ORDER
C
      DO 40 H = 1,NOH
      DO 30 K = 1,NK
   30 S%QK(K,H) = (0.0D0,0.0D0)
      DO 36 J = 1,NJ
      Q = S%B(J,H)
      DO 34 N = S%KP(J),S%KP(J+1)-1
      K = S%KR(N)
      S%QK(K,H) = S%QK(K,H) + S%KV(N)*Q
   34 CONTINUE
   36 CONTINUE
   40 CONTINUE
C
C     QIH = GKI(T) QKH: EACH QIH(I,H) A SUM OVER K IN ORDER
C
      DO 60 H = 1,NOH
      DO 60 I = 1,NOH
      ACC = (0.0D0,0.0D0)
      DO 50 K = 1,NK
      ACC = ACC + GK(K,I)*S%QK(K,H)
   50 CONTINUE
      S%QI(I,H) = ACC
   60 CONTINUE
      S%IOK = 2
      RETURN
      END

      SUBROUTINE AMPKW (S,IP,NK,NOH,BUF,NDONE,IERR)
C
C     HALO: AMPK'S WRITE OF PAIR IP: ITS QKH ONTO QJHL (WHEN WANTED) AND
C     ITS QIH ONTO QHHL, NOH COLUMNS EACH, AS AMPD'S CYCT2B COPIES DO.
C     UNDER AMPK'S GINO DEPENDENCE, IN PAIR ORDER.
C
      USE AMPKM
      TYPE(AMPKS)      S
      INTEGER          IP,NK,NOH,BUF(1),NDONE,IERR,H,QHHCOL,AJJCOL,
     1                 IFILE
      COMMON /AMPCOM/  NCOL,NSUB,XM,XK,AJJCOL,QHHCOL,NGP,NGPD(2,30),
     1                 MCBQHH(7),MCBQJH(7)
      COMMON /PACKX /  ITC1,ITC2,II1,JJ1,INCR1
C
C     IN ORDER: NOTHING AFTER A PAIR THAT WAS NOT WRITTEN (THE TIME RAN
C     OUT BEFORE IT WAS READ, OR ITS PIVOT VANISHED - IERR)
C
      IF (NDONE .NE. IP-1) RETURN
      IF (S%IOK.EQ.-1 .AND. IERR.EQ.0) IERR = IP
      IF (S%IOK .NE. 2) RETURN
      IF (MCBQJH(1) .LE. 0) GO TO 30
      MCBQJH(3) = NK
      IFILE = MCBQJH(1)
      CALL GOPEN (IFILE,BUF,3)
      DO 20 H = 1,NOH
      ITC1  = 4
      ITC2  = MCBQJH(5)
      II1   = 1
      JJ1   = NK
      INCR1 = 1
      CALL PACK (S%QK(1,H),IFILE,MCBQJH)
   20 CONTINUE
      CALL CLOSE (IFILE,3)
   30 IFILE = MCBQHH(1)
      CALL GOPEN (IFILE,BUF,3)
      DO 40 H = 1,NOH
      ITC1  = 4
      ITC2  = MCBQHH(5)
      II1   = 1
      JJ1   = NOH
      INCR1 = 1
      CALL PACK (S%QI(1,H),IFILE,MCBQHH)
   40 CONTINUE
      CALL CLOSE (IFILE,3)
      NDONE = IP
      RETURN
      END
