      SUBROUTINE FA1PKT (AZ,AMK,AMB,N,E1,IROOT,IBUF)
C
C     HALO: THE EIGENVECTOR OF ONE ACCEPTED PK ROOT, KEPT ON SCRATCH
C     FILE 302 - ONE RECORD OF 2N WORDS (N COMPLEX) PER ROOT OF THE
C     LOOP, IN THE ORDER THE ROOTS ARE ACCEPTED - FOR THE ROOT TRACKING
C     OF FA1PKU. THE MATRIX AND THE SOLVER ARE FA1PKV'S: THE VECTOR OF
C     P**2 + P M-1 B + M-1 K AT THE ROOT P, WITH M-1 B AND M-1 K AS
C     FA1PKE HOLDS THEM AT THE REDUCED FREQUENCY THE ROOT CONVERGED AT.
C
C     AZ     WORK, AT LEAST 2N*N + 8N COMPLEX WORDS (FA1PKE'S Z(IMA))
C     AMK    M-1 K (N BY N REAL, COLUMN STORED), FA1PKE'S Z(IV)
C     AMB    M-1 B, FA1PKE'S Z(IB)
C     E1     THE ROOT'S FIVE WORDS (RE, IM, K, F, G)
C     IROOT  ROOTS ACCEPTED BEFORE THIS ONE (0 STARTS THE FILE)
C     IBUF   A GINO BUFFER
C
      INTEGER         IBUF(1),IROOT,N,N2,NA,NB,NC,ND,I,J,K
      REAL            E1(5),E(2),AMK(1),AMB(1)
      COMPLEX         AZ(1),CEIG,EIGEN,EIGZ
      EQUIVALENCE     (EIGEN,E(1))
      DATA    ISCR  / 302 /
C
      EIGZ = (0.0,0.0)
      IF (N .LT. 2) GO TO 100
      E(1) = E1(1)
      E(2) = E1(2)
C
C     A = P**2 I + P M-1 B + M-1 K, AS FA1PKV BUILDS IT
C
      CEIG = EIGEN*EIGEN
      K = 0
      DO 10 I = 1,N
      DO 10 J = 1,N
      K = K + 1
      AZ(K) = -AMB(K)*EIGEN - AMK(K)
      IF (I .EQ. J) AZ(K) = AZ(K) + CEIG
   10 CONTINUE
      N2 = N*2
      NA = 1  + N2*N
      NB = NA + N2
      NC = NB + N2
      ND = NC + N2
      CALL EGNVCT (AZ,AZ(NA),EIGZ,AZ(NB),AZ(NC),AZ(ND),N)
      CALL FA1PKX (AZ(NB),N,IROOT,IBUF)
  100 RETURN
      END

      SUBROUTINE FA1PKX (VEC,N,IROOT,IBUF)
C
C     HALO: FA1PKT'S RECORD OF ONE ROOT'S EIGENVECTOR (VEC, N COMPLEX)
C     ON SCRATCH 302, THE FILE STARTED AT THE LOOP'S FIRST ROOT
C     (IROOT = 0). SEPARATE SO THAT THE PARALLEL PK SOLVE (FA1PKP) CAN
C     WRITE THE VECTORS IT COMPUTED IN ITS THREADS, IN THIS ORDER.
C
      INTEGER         IBUF(1),IROOT,N
      REAL            VEC(1)
      DATA    ISCR  / 302 /
C
      IF (N .LT. 2) GO TO 100
      IF (IROOT .EQ. 0) CALL OPEN (*100,ISCR,IBUF,1)
      IF (IROOT .NE. 0) CALL OPEN (*100,ISCR,IBUF,3)
      CALL WRITE (ISCR,VEC,2*N,1)
      CALL CLOSE (ISCR,2)
  100 RETURN
      END

      SUBROUTINE FA1PKU (ROOTS,NROOT,N,W,NW,MXHH,IBUF,FLOOP,XMACH)
C
C     HALO: ROOT TRACKING ACROSS THE FLUTTER LOOPS. THE ROOTS OF THIS
C     LOOP (FIVE WORDS EACH - RE, IM, K, F, G - ACCEPTED IN ASCENDING
C     FREQUENCY, WHICH IS WHY A ROOT CHANGES ITS PLACE WHERE TWO OF THEM
C     CROSS IN FREQUENCY) ARE RE-ORDERED SO THAT ROOT I FOLLOWS ROOT I
C     OF THE LOOP BEFORE: EVERY PAIR (PREVIOUS I, CURRENT J) COSTS
C     (1 - MAC) + A QUARTER OF THE RELATIVE DISTANCE OF THE EIGENVALUES,
C     THE MAC THE MODAL ASSURANCE CRITERION OF THE TWO PK EIGENVECTORS
C     (FA1PKT'S,
C     ON SCRATCH 302), AND THE PAIRS ARE ASSIGNED GREEDILY OVER
C     INCREASING COST; ROOTS THE PREVIOUS LOOP DID NOT HAVE TAKE THE
C     PLACES LEFT, IN THEIR OWN ORDER. THE VECTORS OF THIS LOOP ARE THEN
C     KEPT ON MXHH (WHICH THE PK METHOD DOES NOT USE) FOR THE NEXT LOOP.
C     THE TRACKING RESTARTS ON THE FIRST LOOP AND WHEN THE MACH CHANGES,
C     AND IS SKIPPED, WITH A NOTE, WHEN THE WORK SPACE IS TOO SMALL.
C
C     ROOTS  THE LOOP'S ROOTS, 5 BY NROOT, RE-ORDERED IN PLACE
C     W      WORK OF NW WORDS (FA1PKE'S FREE CORE BELOW THE Q TABLES)
C     MXHH   THE DATA BLOCK THAT CARRIES THE VECTORS BETWEEN LOOPS
C     FLOOP  THE LOOP NUMBER, XMACH THE LOOP'S MACH
C
      INTEGER         NROOT,N,NW,MXHH,IBUF(1),FLOOP,HDR(3)
      REAL            ROOTS(5,1),W(1),XMACH,RHDR(3)
      INTEGER         N2,ICUR,IPRV,ICST,IORD,ITAK,ITMP,NEED,NPREV,I,J,K
      INTEGER         IBEST,JBEST,NWR,IC,IP,L,IPEV,NSWAP
      REAL            CBEST
      DOUBLE PRECISION VWR,VWI,VV,WW,DMAC,DLAM,DLAMR
      COMMON /SYSTEM/ SYSBUF,NOUT
      EQUIVALENCE     (HDR(1),RHDR(1))
      DATA    ISCR  / 302 /
C
      IF (NROOT .LE. 0 .OR. N .LT. 2) GO TO 900
      N2 = N*2
C
C     CORE: THIS LOOP'S VECTORS, THE PREVIOUS LOOP'S, THE COST MATRIX,
C     THE ORDER, THE TAKEN FLAGS, AND A COPY FOR THE PERMUTATION
C
      ICUR = 1
      IPRV = ICUR + N2*NROOT
      IPEV = IPRV + N2*NROOT
      ICST = IPEV + 2*NROOT
      IORD = ICST + NROOT*NROOT
      ITAK = IORD + NROOT
      ITMP = ITAK + NROOT
      NEED = ITMP + N2*NROOT
      IF (NEED .LE. NW) GO TO 10
      WRITE (NOUT,5) NEED,NW
    5 FORMAT (1H0,'*** ROOT TRACKING SKIPPED ON THIS LOOP: ',I9,
     1        ' WORDS OF WORK SPACE WANTED, ',I9,' AVAILABLE')
      GO TO 900
C
C     THIS LOOP'S VECTORS, IN ACCEPTANCE ORDER
C
   10 CALL OPEN (*900,ISCR,IBUF,0)
      DO 20 J = 1,NROOT
      CALL READ (*30,*20,ISCR,W(ICUR+(J-1)*N2),N2,1,NWR)
   20 CONTINUE
   30 CALL CLOSE (ISCR,1)
C
C     THE PREVIOUS LOOP'S, WHEN THERE IS ONE AT THIS MACH
C
      NPREV = 0
      IF (FLOOP .LE. 1) GO TO 100
      CALL GOPEN (MXHH,IBUF,0)
      CALL READ (*90,*90,MXHH,HDR,3,1,NWR)
      IF (HDR(1) .LE. 0 .OR. HDR(2) .NE. N) GO TO 90
      IF (RHDR(3) .NE. XMACH) GO TO 90
      NPREV = HDR(1)
      IF (NPREV .GT. NROOT) NPREV = NROOT
      DO 40 I = 1,NPREV
      CALL READ (*90,*90,MXHH,W(IPEV+(I-1)*2),2,0,NWR)
      CALL READ (*90,*40,MXHH,W(IPRV+(I-1)*N2),N2,1,NWR)
   40 CONTINUE
      GO TO 95
   90 NPREV = 0
   95 CALL CLOSE (MXHH,1)
  100 CONTINUE
      IF (NPREV .LE. 0) GO TO 500
C
C     THE COST OF PAIRING PREVIOUS ROOT I WITH CURRENT ROOT J
C
      DO 200 I = 1,NPREV
      IP = IPRV + (I-1)*N2
      VV = 0.D0
      DO 110 K = 1,N2
  110 VV = VV + DBLE(W(IP+K-1))**2
      DO 190 J = 1,NROOT
      IC = ICUR + (J-1)*N2
      WW  = 0.D0
      VWR = 0.D0
      VWI = 0.D0
      DO 120 K = 1,N
      L = 2*(K-1)
      WW  = WW  + DBLE(W(IC+L))**2 + DBLE(W(IC+L+1))**2
      VWR = VWR + DBLE(W(IP+L))*W(IC+L)   + DBLE(W(IP+L+1))*W(IC+L+1)
      VWI = VWI + DBLE(W(IP+L))*W(IC+L+1) - DBLE(W(IP+L+1))*W(IC+L)
  120 CONTINUE
      DMAC = 0.D0
      IF (VV .GT. 0.D0 .AND. WW .GT. 0.D0)
     1    DMAC = (VWR*VWR + VWI*VWI)/(VV*WW)
C
C     THE DISTANCE BETWEEN THE CURRENT ROOT J AND THE PREVIOUS LOOP'S
C     ROOT I (ITS EIGENVALUE KEPT AHEAD OF ITS VECTOR ON MXHH), RELATIVE
C     TO THE SIZE OF THE LATTER; NEXT TO THE MAC A TIE-BREAKER
C
      DLAMR = SQRT(DBLE(W(IPEV+(I-1)*2))**2 +
     1             DBLE(W(IPEV+(I-1)*2+1))**2)
      IF (DLAMR .LT. 1.D-6) DLAMR = 1.D-6
      DLAM  = SQRT((DBLE(ROOTS(1,J)) - W(IPEV+(I-1)*2))**2 +
     1             (DBLE(ROOTS(2,J)) - W(IPEV+(I-1)*2+1))**2)/DLAMR
      IF (DLAM .GT. 2.D0) DLAM = 2.D0
      W(ICST + (I-1)*NROOT + J - 1) = (1.D0 - DMAC) + 0.25D0*DLAM
  190 CONTINUE
  200 CONTINUE
C
C     GREEDY ASSIGNMENT OVER INCREASING COST
C
      DO 210 I = 1,NROOT
      W(IORD+I-1) = 0.0
  210 W(ITAK+I-1) = 0.0
      DO 260 K = 1,NPREV
      CBEST = 1.E30
      IBEST = 0
      JBEST = 0
      DO 240 I = 1,NPREV
      IF (W(IORD+I-1) .NE. 0.0) GO TO 240
      DO 230 J = 1,NROOT
      IF (W(ITAK+J-1) .NE. 0.0) GO TO 230
      IF (W(ICST+(I-1)*NROOT+J-1) .GE. CBEST) GO TO 230
      CBEST = W(ICST+(I-1)*NROOT+J-1)
      IBEST = I
      JBEST = J
  230 CONTINUE
  240 CONTINUE
      IF (IBEST .EQ. 0) GO TO 270
      W(IORD+IBEST-1) = JBEST
      W(ITAK+JBEST-1) = 1.0
  260 CONTINUE
  270 CONTINUE
C
C     THE ROOTS THE PREVIOUS LOOP DID NOT HAVE FILL THE FREE PLACES
C
      J = 0
      DO 290 I = 1,NROOT
      IF (W(IORD+I-1) .NE. 0.0) GO TO 290
  280 J = J + 1
      IF (W(ITAK+J-1) .NE. 0.0) GO TO 280
      W(IORD+I-1) = J
      W(ITAK+J-1) = 1.0
  290 CONTINUE
C
C     PERMUTE THE ROOT RECORDS AND THE VECTORS
C
      DO 320 I = 1,NROOT
      J = W(IORD+I-1)
      DO 310 K = 1,5
  310 W(ITMP+(I-1)*5+K-1) = ROOTS(K,J)
  320 CONTINUE
      DO 340 I = 1,NROOT
      DO 330 K = 1,5
  330 ROOTS(K,I) = W(ITMP+(I-1)*5+K-1)
  340 CONTINUE
      DO 360 I = 1,NROOT
      J = W(IORD+I-1)
      DO 350 K = 1,N2
  350 W(ITMP+(I-1)*N2+K-1) = W(ICUR+(J-1)*N2+K-1)
  360 CONTINUE
      DO 380 K = 1,N2*NROOT
  380 W(ICUR+K-1) = W(ITMP+K-1)
      NSWAP = 0
      DO 390 I = 1,NROOT
      IF (W(IORD+I-1) .NE. FLOAT(I)) NSWAP = NSWAP + 1
  390 CONTINUE
      IF (NSWAP .GT. 0) WRITE (NOUT,395) FLOOP,NSWAP,NROOT
  395 FORMAT (1H0,'*** ROOT TRACKING: FLUTTER LOOP',I5,' - ',I4,' OF',
     1        I4,' ROOTS TOOK ANOTHER PLACE TO FOLLOW THE LOOP BEFORE')
C
C     THIS LOOP'S VECTORS, IN THEIR NEW ORDER, FOR THE NEXT LOOP
C
  500 CALL GOPEN (MXHH,IBUF,1)
      HDR(1)  = NROOT
      HDR(2)  = N
      RHDR(3) = XMACH
      CALL WRITE (MXHH,HDR,3,1)
      DO 510 J = 1,NROOT
      CALL WRITE (MXHH,ROOTS(1,J),2,0)
      CALL WRITE (MXHH,W(ICUR+(J-1)*N2),N2,1)
  510 CONTINUE
      CALL CLOSE (MXHH,1)
  900 RETURN
      END
