      MODULE FA1PKM
C
C     HALO: WHAT THE PARALLEL PK SOLVE (FA1PKP) KEEPS OF EACH FLUTTER
C     LOOP UNTIL FA1PKE REACHES THAT LOOP AND WRITES IT (FA1PKR).
C
C     ROOTS   THE ACCEPTED ROOTS, 5 WORDS EACH (RE, IM, K, F, G), IN
C             ACCEPTANCE ORDER, AS FA1PKE KEEPS THEM AT Z(IEIGNS+1)
C     VT      EACH ACCEPTED ROOT'S EIGENVECTOR (N COMPLEX), WHAT FA1PKT
C             WRITES TO SCRATCH 302 FOR THE ROOT TRACKER
C     EVK     THE PRINTED EVENTS OF THE LOOP, IN THE ORDER THE SERIAL
C             SOLVE MAKES THEM: 1 = AN EIGENVECTOR FA1PKV PRINTS AND
C             WRITES TO 301 (EVE ITS 5 WORDS, EVV ITS VECTOR), 2 = THE
C             'PK METHOD FAILED TO CONVERGE' WARNING (EVI = NIT, NROOT)
C     IERR    1 WHEN THE ROOT LIST RAN OUT BEFORE NEIW ROOTS (FA1PKE'S
C             SYSTEM FATAL AT 360), WITH IMHERE, LERR, JERR TO PRINT
C
      TYPE PKLOOP
         INTEGER              :: DONE = 0
         INTEGER              :: NROOT = 0, NEV = 0, NPV = 0
         INTEGER              :: IERR = 0, IMHERE = 0
         INTEGER              :: LERR = 0, JERR = 0
         REAL,    ALLOCATABLE :: ROOTS(:,:), VT(:,:)
         REAL,    ALLOCATABLE :: EVE(:,:), EVV(:,:)
         INTEGER, ALLOCATABLE :: EVK(:), EVI(:,:)
      END TYPE
      TYPE(PKLOOP), ALLOCATABLE, SAVE :: LOOPS(:)
      INTEGER, SAVE :: MLOOPS = 0
      END MODULE

      SUBROUTINE FA1PKP (FLOOP,NLOOP,N,NK,NEIW,EPS,BREF,RREF,ZMV,
     1                   ZMH,ZBH,ZKH,ZQ,DA,ZK,NTHR)
C
C     HALO: THE PK METHOD'S FLUTTER LOOPS, SOLVED SIDE BY SIDE.
C
C     FA1 CALLS FA1PKE ONCE PER LOOP (ONE MATCHED POINT: A DENSITY,
C     MACH AND VELOCITY) AND FA1PKE SOLVES IT FROM K = 0 WITH NOTHING
C     CARRIED OVER FROM THE LOOP BEFORE, SO THE LOOPS AT ONE MACH (ONE
C     SET OF INTERPOLATED Q TABLES, WHICH FA1PKI REBUILDS WHEN THE MACH
C     CHANGES) ARE INDEPENDENT. ON THE FIRST LOOP OF SUCH A GROUP THIS
C     SOLVES THEM ALL, ONE OPENMP THREAD PER LOOP, AND KEEPS WHAT EACH
C     LOOP WOULD HAVE WRITTEN (MODULE FA1PKM); FA1PKE THEN WRITES LOOP
C     BY LOOP, IN ORDER, WHAT THE SERIAL SOLVE WOULD HAVE (FA1PKR). THE
C     ROOT TRACKER (FA1PKU) STAYS SERIAL, IN FA1PKE, WHERE IT WAS.
C
C     EACH LOOP IS FA1PKE'S OWN ARITHMETIC (FA1PKL, TRANSCRIBED FROM IT
C     STATEMENT FOR STATEMENT) ON ARRAYS OF ITS OWN, SO THE PRINT FILE
C     IS THE SERIAL RUN'S TO THE BIT; N95_PK_THREADS=1 IN THE
C     ENVIRONMENT GIVES THE SERIAL SOLVE BACK, WHICH IS HOW THAT IS
C     CHECKED.
C
C     FLOOP   THE LOOP FA1PKE IS ON (THE FIRST OF THE GROUP)
C     ZMV     FA1PKE'S Z(IMVR): MACH, VELOCITY, DENSITY PER LOOP
C     ZMH..DA FA1PKE'S MATRICES AND FA1PKI'S TABLES, READ ONLY
C     NTHR    THREADS TO USE (0 = THE OPENMP DEFAULT)
C
      USE FA1PKM
      INTEGER          FLOOP,NLOOP,N,NK,NEIW,NTHR,L,LEND,NEIGN,NEVMX,
     1                 NN,NN2,KN1
      REAL             EPS,BREF,RREF,ZMV(1),ZMH(1),ZBH(1),ZKH(1),ZQ(1),
     1                 ZK(1),XMACH
      DOUBLE PRECISION DA(1)
      REAL,             ALLOCATABLE :: T(:),BW(:),V(:),EIV(:),QW(:),
     1                                 CZ(:)
      DOUBLE PRECISION, ALLOCATABLE :: DP(:),DC(:)
!$    INTEGER          OMP_GET_MAX_THREADS
C
C     THE LOOPS' RECORDS, FRESH FOR A NEW SET OF LOOPS
C
      IF (ALLOCATED(LOOPS) .AND. (MLOOPS.NE.NLOOP .OR. FLOOP.EQ.1))
     1   DEALLOCATE (LOOPS)
      IF (.NOT.ALLOCATED(LOOPS)) THEN
         ALLOCATE (LOOPS(NLOOP))
         MLOOPS = NLOOP
      END IF
C
C     THE GROUP: FLOOP AND THE LOOPS AFTER IT AT THE SAME MACH (FA1PKI'S
C     TEST, EXACT EQUALITY)
C
      XMACH = ZMV((FLOOP-1)*3+1)
      LEND  = FLOOP
   10 IF (LEND .GE. NLOOP) GO TO 20
      IF (ZMV(LEND*3+1) .NE. XMACH) GO TO 20
      LEND = LEND + 1
      GO TO 10
   20 CONTINUE
      NEIGN = N*2
      NEVMX = NEIGN + 2*NEIW + 2
      NN    = N*N
      NN2   = NN*2
      KN1   = NK + 1
!$    IF (NTHR .LE. 0) NTHR = OMP_GET_MAX_THREADS()
      IF (NTHR .LE. 0) NTHR = 1
C
C
C     EACH THREAD'S ARRAYS. BW HOLDS FA1PKE'S Z(IB) (M-1 B, NN WORDS)
C     AND, AT THE SAME DISTANCE ABOVE IT AS IN OPEN CORE, Z(IMA) (THE
C     (2N)**2 DOUBLE PRECISION QR WORK OF FA1PKQ). NASA'S ATEIG READS
C     ONE DOUBLE BELOW ITS MATRIX (SEE FA1PKQ.F) - IN FA1PKE THE TOP OF
C     M-1 B - AND WHAT IT FINDS THERE STEERS THE QR SWEEP, SO THE SAME
C     BYTES HAVE TO BE THERE FOR THE SAME ROOTS. Z(IB) IS ODD IN FA1PKE
C     (ICP IS), SO Z(IMA) IS Z(IB+NN), OR Z(IB+NN+1) WHEN NN IS ODD.
C     THE DOUBLE IS 4N WORDS BELOW Z(IMA), INSIDE M-1 B FOR N .GE. 4;
C     FA1PKE KEEPS THE SERIAL SOLVE FOR A SMALLER BASIS.
C
!$OMP PARALLEL NUM_THREADS(NTHR) DEFAULT(SHARED)
!$OMP&  PRIVATE(L,T,BW,V,EIV,QW,CZ,DP,DC)
      ALLOCATE (T(NN),BW(NN+1+8*NN+2),V(NN),EIV(4*N+4),QW(NN2),
     1          CZ(2*(2*NN+12*N+8)),DP(KN1+1),DC(KN1+1))
      BW = 0.0
!$OMP DO SCHEDULE(DYNAMIC,1)
      DO 100 L = FLOOP,LEND
      IF (LOOPS(L)%DONE .NE. 0) GO TO 100
      CALL FA1PKL (L,N,NK,NEIW,EPS,BREF,RREF,ZMV,ZMH,ZBH,ZKH,ZQ,DA,ZK,
     1             T,BW,BW(1+NN+MOD(NN,2)),V,EIV,QW,CZ,DP,DC,
     2             NEVMX)
  100 CONTINUE
!$OMP END DO
      DEALLOCATE (T,BW,V,EIV,QW,CZ,DP,DC)
!$OMP END PARALLEL
      RETURN
      END

      SUBROUTINE FA1PKL (L,N,NK,NEIW,EPS,BREF,RREF,ZMV,ZMH,ZBH,ZKH,ZQ,
     1                   DA,ZK,T,B,AW,V,EIV,QW,CZ,DP,DC,NEVMX)
C
C     HALO: ONE FLUTTER LOOP OF THE PK METHOD - FA1PKE FROM LABEL 100 TO
C     LABEL 300, STATEMENT FOR STATEMENT, ON ARRAYS OF ITS OWN INSTEAD
C     OF OPEN CORE, WITH FA1PKT'S AND FA1PKV'S EIGENVECTORS COMPUTED
C     HERE AND KEPT (MODULE FA1PKM) FOR FA1PKR TO WRITE IN ORDER. THE
C     COMMENTS AND LABELS ARE FA1PKE'S. NOT FOR DIAG 39 (FA1PKE KEEPS
C     THE SERIAL SOLVE THEN), SO NOTHING HERE PRINTS.
C
C     FA1PKE'S Z(IT)  ->  T (THE MATRIX) AND EIV (THE EIGENVALUES)
C             Z(IB), Z(IV), Z(IMA) -> B, V, AW (B AND AW IN ONE ARRAY,
C             AS FA1PKP LAYS THEM OUT)
C             Z(IQ0+1..) -> QW,  DZ(IP0D+..) -> DP,  DZ(IC0D+..) -> DC
C             Z(NL+I) -> EIV(NLO+I+1),  Z(K..) -> ROOTS(1..5,NROOT+1)
C
      USE FA1PKM
      INTEGER          L,N,NK,NEIW,NEVMX,NROW,NEIGN,KN1,NIT,NROOT,NN,
     1                 NN2,I,J,K,LL,NLFT,NLO,NR,NRS,NRA,IMHERE,IE,KR
      REAL             EPS,BREF,RREF,ZMV(1),ZMH(1),ZBH(1),ZKH(1),ZQ(1),
     1                 ZK(1),T(1),B(1),V(1),EIV(1),QW(1),CZ(1)
      REAL             KINT,VEL,VELS,RHO,XAV,YAV1,X10,X11,X12,Y10,Y11,
     1                 BOV,RBV,RVS,RKTST,XAV1,D1,A11,A10
      DOUBLE PRECISION DA(1),AW(1),DP(1),DC(1),DX1,DX2,DSUM
      LOGICAL          EIGV
      COMMON /CONDAS/  PI,TWOPI
C
      NROW  = N
      NEIGN = NROW*2
      NN    = NROW*NROW
      NN2   = NN*2
      KN1   = NK + 1
      LOOPS(L)%NROOT = 0
      LOOPS(L)%NEV   = 0
      LOOPS(L)%NPV   = 0
      LOOPS(L)%IERR  = 0
      IF (.NOT.ALLOCATED(LOOPS(L)%ROOTS))
     1   ALLOCATE (LOOPS(L)%ROOTS(5,NEIW),LOOPS(L)%VT(2*N,NEIW),
     2             LOOPS(L)%EVK(NEVMX),LOOPS(L)%EVI(2,NEVMX),
     3             LOOPS(L)%EVE(5,NEVMX))
C
C     START OF LARGE LOOP WITH K = 0.0
C
      KINT = 0.0
      I    = (L-1)*3
      EIGV = .FALSE.
      IF (ZMV(I+2) .LT. 0.0) EIGV = .TRUE.
      VEL  = ABS(ZMV(I+2))
      VELS = VEL*VEL
      RHO  = (RREF*ZMV(I+3))/2.0
      IF (EIGV .AND. .NOT.ALLOCATED(LOOPS(L)%EVV))
     1   ALLOCATE (LOOPS(L)%EVV(2*N,NEVMX))
      NIT   = 0
      NROOT = 0
C
C     INITIALIZE LEAST SQUARE COEFFCIENTS
C
      XAV   = 0.
      YAV1  = 0.
      X10   = 0.
      X11   = 0.
      X12   = 0.
      Y10   = 0.
      Y11   = 0.
C
C     BUILD P
C
  110 CONTINUE
      NIT = NIT + 1
C
C     SUM LEAST SQUARE COEFFICIENTS ASSOCIATED WITH INDEPENDENT
C     VARIABLE STARTING WITH SECOND TRIAL
C
      IF (NIT .EQ. 1) GO TO 115
      XAV = XAV + KINT
      X10 = X10 + 1.
      X11 = X11 + KINT
      X12 = X12 + KINT**2
C
  115 DX1  = KINT
      DO 120 I = 1,NK
      DX2 = ZK(I)
      DP(I) = DABS((DX1-DX2)**3) + (DX1+DX2)**3
  120 CONTINUE
      DP(KN1) = 1.D0
C
C     FIND C = A-1  P
C
      LL = 1
      DO 135 I = 1,KN1
      DSUM = 0.D+0
      DO 130 J = 1,KN1
      DSUM = DSUM + DA(LL)*DP(J)
      LL = LL + 1
  130 CONTINUE
      DC(I) = DSUM
  135 CONTINUE
C
C     FIND QR AND QI = Q  C  Q IS COLUMN STORED
C
      LL = 1
      DO 145 I = 1,NN2
      DSUM = 0.D+0
      DO 140 J = 1,NK
      K = LL + (J-1)*NN2
      DSUM = DSUM + ZQ(K)*DC(J)
  140 CONTINUE
      LL = LL + 1
      QW(I) = DSUM
  145 CONTINUE
C
C     B  =  -BHH  + RHO*BREF*VEL  QHHI
C     K  =  -KHH  + RHO*VELS      QHHR
C
      BOV = BREF/VEL
      RBV = RHO*BREF*VEL
      RVS = RHO*VELS
      DO 150 I = 1,NN
      T(I) = -ZBH(I) + RBV*QW(NN+I)
      B(I) = -ZKH(I) + RVS*QW(I)
  150 CONTINUE
      CALL FA1PKG (B,ZMH,V,NROW)
      CALL FA1PKG (T,ZMH,B,NROW)
      CALL FA1PKQ (AW,V,B,EIV,NROW)
C
C     SORT EIGENVALUES
C
      J = NEIGN*2
      CALL FA1PKS (2,1,EIV,J)
      CALL FA1PKS (2,2,EIV,J)
      IF (KINT .NE. 0.0) GO TO 180
      NLFT = NEIGN
      DO 160 I = 1,J,2
      IF (EIV(I+1) .GE. 0.0) GO TO 170
      NLFT = NLFT - 1
  160 CONTINUE
  170 NLO = (NEIGN-NLFT)*2
      NR  = 0
      DO 175 I = 1,J,2
      IF (EIV(I+1) .NE. 0.0) GO TO 175
      NR = NR + 1
      IF (.NOT.EIGV) GO TO 175
C     FA1PKV (Z(IMA),Z(IV),Z(IB),NROW,Z(IT+I-1),...): A REAL ROOT OF
C     THE FIRST SOLVE, ITS TWO WORDS (FA1PKV READS NO MORE OF A ROOT
C     WHOSE IMAGINARY PART IS ZERO)
      CALL FA1PKY (L,1,0,EIV(I),EIV(I+1),0.0,0.0,0.0,V,B,CZ,NROW)
  175 CONTINUE
      NRS = NR + 1
      NR  = NR/2
      NRA = 0
  180 CONTINUE
C
C     ROOT ACCEPTANCE AND SAVING
C
  200 J  = NLFT*2
      LL = NROOT*2 + 1 + NRA*2
      IMHERE = 200
      IF (LL .GT. J) GO TO 360
C
      DO 270 I = LL,J,2
      KR = NROOT + 1
      IF (EIV(NLO+I+1) .NE. 0.0) GO TO 220
      IF (KINT         .NE. 0.0) GO TO 220
      IF (NRS .NE. NR) NRS = NRS - 1
      IF (NRS .NE. NR) GO TO 270
      NRA = NRA + 1
      LOOPS(L)%ROOTS(1,KR) = EIV(NLO+I)
      LOOPS(L)%ROOTS(2,KR) = EIV(NLO+I+1)
      LOOPS(L)%ROOTS(3,KR) = 0.0
      LOOPS(L)%ROOTS(4,KR) = 0.0
      LOOPS(L)%ROOTS(5,KR) = (BREF/(.34657*VEL))*EIV(NLO+I)
C
C     HALO: THE ROOT'S EIGENVECTOR, FOR THE TRACKING (FA1PKT)
C
  210 CALL FA1PKY (L,3,KR,LOOPS(L)%ROOTS(1,KR),LOOPS(L)%ROOTS(2,KR),
     1             0.0,0.0,0.0,V,B,CZ,NROW)
      NROOT = NROOT + 1
      NIT = 0
C
C     NO. OF ITERATIONS RESET TO ZERO. RE-INITIALIZE LEASE SQUARE COEFF.
C
      XAV = 0.
      YAV1= 0.
      X10 = 0.
      X11 = 0.
      X12 = 0.
      Y10 = 0.
      Y11 = 0.
      IF (NROOT .GE. NEIW) GO TO 300
      GO TO 270
C
  220 RKTST = BOV*EIV(NLO+I+1)
      IF (ABS(RKTST-KINT) .LT. EPS) GO TO 230
      IF (RKTST .EQ. 0.0) GO TO 230
C
C     SUM LEAST SQUARE COEFFICIENTS ASSOCIATED WITH DEPENDENT VARIABLE
C
      IF (NIT .EQ. 1) GO TO 225
      YAV1 = YAV1 + RKTST
      Y10  = Y10  + RKTST
      Y11  = Y11  + RKTST*KINT
  225 KINT = RKTST
      IF (NIT .EQ. 10) GO TO 240
      GO TO 110
C
  230 LOOPS(L)%ROOTS(1,KR) = EIV(NLO+I)
      LOOPS(L)%ROOTS(2,KR) = EIV(NLO+I+1)
      LOOPS(L)%ROOTS(3,KR) = RKTST
      LOOPS(L)%ROOTS(4,KR) = (1.0/TWOPI)*EIV(NLO+I+1)
      IF (EIV(NLO+I+1) .NE. 0.0) LOOPS(L)%ROOTS(5,KR) =
     1   (2.0*EIV(NLO+I))/EIV(NLO+I+1)
      IF (EIV(NLO+I+1) .EQ. 0.0) LOOPS(L)%ROOTS(5,KR) =
     1   (BREF/(.34657*VEL))*EIV(NLO+I)
      IF (EIGV) CALL FA1PKY (L,1,0,LOOPS(L)%ROOTS(1,KR),
     1   LOOPS(L)%ROOTS(2,KR),LOOPS(L)%ROOTS(3,KR),
     2   LOOPS(L)%ROOTS(4,KR),LOOPS(L)%ROOTS(5,KR),V,B,CZ,NROW)
      GO TO 210
C
C     LEAST SQUARES FIT APPROXIMATION TO FIND CONVERGED ROOT
C
  240 NIT  = NIT + 1
      XAV1 = XAV/(NIT-2)
      XAV  = (XAV + RKTST)/(NIT-1)
      YAV1 = YAV1/(NIT-2)
      D1   = X12*X10  - X11*X11
      A11  = (X10*Y11 - X11*Y10)/D1
      A10  = (X12*Y10 - X11*Y11)/D1
      RKTST= -A10/(A11-1.)
C     THE WARNING FA1PKE PRINTS HERE (FORMAT 250), FOR FA1PKR
      IE = LOOPS(L)%NEV + 1
      LOOPS(L)%NEV = IE
      LOOPS(L)%EVK(IE)   = 2
      LOOPS(L)%EVI(1,IE) = NIT
      LOOPS(L)%EVI(2,IE) = NROOT
      GO TO 230
  270 CONTINUE
      IMHERE = 270
      GO TO 360
C
C     THE LOOP'S ROOTS ARE ALL IN; FA1PKE TRACKS AND WRITES THEM
C
  300 LOOPS(L)%NROOT = NROOT
      LOOPS(L)%DONE  = 1
      RETURN
C
C     FA1PKE'S SYSTEM FATAL: THE LIST OF ROOTS RAN OUT (FORMAT 370)
C
  360 LOOPS(L)%NROOT  = NROOT
      LOOPS(L)%IERR   = 1
      LOOPS(L)%IMHERE = IMHERE
      LOOPS(L)%LERR   = LL
      LOOPS(L)%JERR   = J
      LOOPS(L)%DONE   = 1
      RETURN
      END

      SUBROUTINE FA1PKY (L,KIND,KR,ER,EI,E3,E4,E5,AMK,AMB,CZ,N)
C
C     HALO: THE EIGENVECTOR OF THE ROOT (ER,EI) OF ONE PK LOOP, AS
C     FA1PKV AND FA1PKT COMPUTE IT (THE VECTOR OF P**2 + P M-1 B + M-1 K
C     AT THE ROOT P, EGNVCT), KEPT FOR FA1PKR. KIND 1 IS AN FA1PKV
C     EVENT (THE ROOT'S 5 WORDS KEPT WITH IT), KIND 3 THE TRACKING
C     VECTOR FA1PKT KEEPS FOR ACCEPTED ROOT KR. THE MATRIX IS BUILT AS
C     FA1PKV AND FA1PKT BUILD IT.
C
      USE FA1PKM
      INTEGER          L,KIND,KR,N,N2,NA,NB,NC,ND,I,J,K,IE,IV
      REAL             ER,EI,E3,E4,E5,AMK(1),AMB(1),E(2)
      COMPLEX          CZ(1),CEIG,EIGEN,EIGZ
      EQUIVALENCE      (EIGEN,E(1))
C
      EIGZ = (0.0,0.0)
      E(1) = ER
      E(2) = EI
      CEIG = EIGEN*EIGEN
      K = 0
      DO 10 I = 1,N
      DO 10 J = 1,N
      K = K + 1
      CZ(K) = -AMB(K)*EIGEN - AMK(K)
      IF (I .EQ. J) CZ(K) = CZ(K) + CEIG
   10 CONTINUE
      N2 = N*2
      NA = 1  + N2*N
      NB = NA + N2
      NC = NB + N2
      ND = NC + N2
      CALL EGNVCT (CZ,CZ(NA),EIGZ,CZ(NB),CZ(NC),CZ(ND),N)
      IF (KIND .EQ. 3) THEN
         DO 20 I = 1,N
         LOOPS(L)%VT(2*I-1,KR) = REAL (CZ(NB+I-1))
         LOOPS(L)%VT(2*I  ,KR) = AIMAG(CZ(NB+I-1))
   20    CONTINUE
      ELSE
         IE = LOOPS(L)%NEV + 1
         IV = LOOPS(L)%NPV + 1
         LOOPS(L)%NEV = IE
         LOOPS(L)%NPV = IV
         LOOPS(L)%EVK(IE)   = 1
         LOOPS(L)%EVI(1,IE) = IV
         LOOPS(L)%EVI(2,IE) = 0
         LOOPS(L)%EVE(1,IE) = ER
         LOOPS(L)%EVE(2,IE) = EI
         LOOPS(L)%EVE(3,IE) = E3
         LOOPS(L)%EVE(4,IE) = E4
         LOOPS(L)%EVE(5,IE) = E5
         DO 30 I = 1,N
         LOOPS(L)%EVV(2*I-1,IV) = REAL (CZ(NB+I-1))
         LOOPS(L)%EVV(2*I  ,IV) = AIMAG(CZ(NB+I-1))
   30    CONTINUE
      END IF
      RETURN
      END

      SUBROUTINE FA1PKR (FLOOP,N,NEIW,BREF,VEL,ROOTS,NROOT,IBUF,IDONE)
C
C     HALO: WRITE FLUTTER LOOP FLOOP AS THE SERIAL PK SOLVE WOULD HAVE,
C     FROM WHAT FA1PKP KEPT: FA1PKV'S EIGENVECTORS (PRINTED, AND ON 301)
C     AND THE NON-CONVERGENCE WARNINGS IN THEIR ORDER, FA1PKT'S VECTORS
C     ON 302, AND THE ROOTS INTO FA1PKE'S Z(IEIGNS+1). IDONE = 0 WHEN
C     THE LOOP WAS NOT SOLVED HERE (FA1PKE THEN SOLVES IT ITSELF), 2 ON
C     THE LIST-RAN-OUT FATAL (PRINTED HERE, FA1PKE STOPS THE RUN).
C
      USE FA1PKM
      INTEGER          FLOOP,N,NEIW,NROOT,IBUF(1),IDONE,IE,I,K,IV,
     1                 SYSBUF,NOUT
      REAL             BREF,VEL,ROOTS(5,1),E1(5)
      CHARACTER        UFM*23,UWM*25,UIM*29,SFM*25
      COMMON /XMSSG /  UFM,UWM,UIM,SFM
      COMMON /SYSTEM/  SYSBUF,NOUT
C
      IDONE = 0
      IF (.NOT.ALLOCATED(LOOPS)) RETURN
      IF (FLOOP.LT.1 .OR. FLOOP.GT.MLOOPS) RETURN
      IF (LOOPS(FLOOP)%DONE .NE. 1) RETURN
      IDONE = 1
      NROOT = 0
      DO 20 IE = 1,LOOPS(FLOOP)%NEV
      IF (LOOPS(FLOOP)%EVK(IE) .EQ. 2) GO TO 10
      DO 5 K = 1,5
    5 E1(K) = LOOPS(FLOOP)%EVE(K,IE)
      IV = LOOPS(FLOOP)%EVI(1,IE)
      CALL FA1PKW (E1,LOOPS(FLOOP)%EVV(1,IV),N,BREF,VEL,IBUF)
      GO TO 20
   10 WRITE  (NOUT,250) UWM,LOOPS(FLOOP)%EVI(1,IE),FLOOP,
     1                  LOOPS(FLOOP)%EVI(2,IE),NEIW
  250 FORMAT (A25,', PK METHOD FIALED TO CONVERGE', /1X,I4,
     1       ' ITERATIONS ON LOOP',I5,',  FOUND',I5,',  ROOTS WANTED',
     2       I5, /5X,'LEAST SQUARES FIT APPROXIMATION IMPLEMENTED.')
   20 CONTINUE
      NROOT = LOOPS(FLOOP)%NROOT
      DO 40 I = 1,NROOT
      CALL FA1PKX (LOOPS(FLOOP)%VT(1,I),N,I-1,IBUF)
      DO 30 K = 1,5
   30 ROOTS(K,I) = LOOPS(FLOOP)%ROOTS(K,I)
   40 CONTINUE
      IF (LOOPS(FLOOP)%IERR .NE. 0) THEN
         WRITE  (NOUT,370) SFM,LOOPS(FLOOP)%IMHERE,LOOPS(FLOOP)%LERR,
     1                     LOOPS(FLOOP)%JERR
  370    FORMAT (A25,'. ERROR IN FA1PKE/@',I3,'  L,J=',2I7)
         IDONE = 2
      END IF
C
C     WRITTEN: LET THE LOOP'S RECORDS GO
C
      LOOPS(FLOOP)%DONE = 2
      IF (ALLOCATED(LOOPS(FLOOP)%ROOTS)) DEALLOCATE (LOOPS(FLOOP)%ROOTS)
      IF (ALLOCATED(LOOPS(FLOOP)%VT))    DEALLOCATE (LOOPS(FLOOP)%VT)
      IF (ALLOCATED(LOOPS(FLOOP)%EVK))   DEALLOCATE (LOOPS(FLOOP)%EVK)
      IF (ALLOCATED(LOOPS(FLOOP)%EVI))   DEALLOCATE (LOOPS(FLOOP)%EVI)
      IF (ALLOCATED(LOOPS(FLOOP)%EVE))   DEALLOCATE (LOOPS(FLOOP)%EVE)
      IF (ALLOCATED(LOOPS(FLOOP)%EVV))   DEALLOCATE (LOOPS(FLOOP)%EVV)
      IF (FLOOP .EQ. MLOOPS) THEN
         DEALLOCATE (LOOPS)
         MLOOPS = 0
      END IF
      RETURN
      END

      SUBROUTINE FA1PKS (NWDS,KEYWX,L,NX)
C
C     HALO: RSORT, FOR THE THREADS OF FA1PKP: THE SAME INSERTION SORT
C     (THE SAME ORDER OF EQUAL KEYS, SO THE SAME RESULT) WITH ITS LOCALS
C     ON THE STACK. RSORT ITSELF IS COMPILED -FNO-AUTOMATIC LIKE THE
C     REST OF THE TREE, SO ITS LOCALS ARE SHARED BY EVERY THREAD.
C
      LOGICAL MAG,BCK
      INTEGER NWDS,KEYWX,NX,KEYWD,NNN,III,IA,I,JJ,II,J,IIA
      REAL    L(1),TEMP(50)
C
      MAG = .FALSE.
      BCK = .FALSE.
      IF (KEYWX .LT. 0) MAG = .TRUE.
      IF (NX    .LT. 0) BCK = .TRUE.
      KEYWD= IABS(KEYWX)
      NNN  = IABS(NX)
      III  = NWDS+KEYWD
      IA   = NWDS-KEYWD
      IF (NNN-NWDS-NWDS .LT. 0) GO TO 150
      DO 140 I = III,NNN,NWDS
      JJ = I-NWDS
      IF (BCK) GO TO 40
      IF (MAG) IF (ABS(L(I))-ABS(L(JJ))) 50,140,140
      IF (L(I)-L(JJ)) 50,140,140
   40 IF (MAG) IF (ABS(L(JJ))-ABS(L(I))) 50,140,140
      IF (L(JJ)-L(I)) 50,140,140
   50 JJ = JJ-NWDS
      IF (JJ .LE. 0) GO TO 70
      IF (BCK) GO TO 60
      IF (MAG) IF (ABS(L(I))-ABS(L(JJ))) 50,80,80
      IF (L(I) - L(JJ)) 50,80,80
   60 IF (MAG) IF (ABS(L(JJ))-ABS(L(I))) 50,80,80
      IF (L(JJ)-L(I)) 50,80,80
   70 JJ = NWDS
      GO TO 90
   80 JJ = JJ+IA+NWDS
   90 II = I-KEYWD
      DO 100 J = 1,NWDS
      II = II+1
  100 TEMP(J) = L(II)
  110 IIA = II-NWDS
      L(II) = L(IIA)
      II = II-1
      IF (II-JJ) 120,120,110
  120 II = II-NWDS
      DO 130 J = 1,NWDS
      II = II+1
  130 L(II) = TEMP(J)
  140 CONTINUE
  150 RETURN
      END
