      SUBROUTINE GENDP (NCARAY,NBARAY,YS,ZS,SG,CG,DT,WORK,MATOUT,IDONE)
C
C     HALO: GEND'S LOOP OVER THE RECEIVING BOXES, THREADED.
C
C     GEND BUILDS THE DOUBLET LATTICE INFLUENCE MATRIX A ROW AT A TIME:
C     FOR EACH RECEIVING BOX I, DPPS SUMS THE KERNEL OF EVERY SENDING
C     BOX INTO DT (SUBP -> SNPDF, INCRO -> TKER, IDF1, IDF2) AND PACK
C     WRITES THE ROW TO THE GINO FILE. THE ROWS ARE INDEPENDENT - THE
C     KERNEL READS THE GEOMETRY AND /AMGMN/, /DLCOM/, AND KEEPS ITS
C     SCRATCH IN /DLM/ AND /KDS/, WHICH ARE THREADPRIVATE (TKER, INCRO
C     AND THE TWO OTHER ROUTINES THAT NAME THEM, FLLD AND SUBB) - SO
C     HERE A BLOCK OF ROWS IS COMPUTED SIDE BY SIDE, ONE OPENMP THREAD
C     PER ROW, INTO DTB, AND THE BLOCK IS PACKED IN ORDER, ROW BY ROW,
C     EXACTLY AS GEND PACKS IT. THE KERNEL ROUTINES ARE COMPILED -O2
C     -FAUTOMATIC -FFP-CONTRACT=OFF: THE SAME ARITHMETIC, SO THE MATRIX
C     IS GEND'S TO THE BIT. ON THE MONARCH (2,282 BOXES) THE KERNEL IS
C     FIVE MILLION BOX PAIRS PER REDUCED FREQUENCY, A SECOND AND A HALF
C     ON ONE THREAD.
C
C     IDONE = 1 WHEN THE MATRIX WAS WRITTEN HERE; 0 SENDS GEND BACK TO
C     ITS OWN LOOP (N95_DLM_THREADS=1 IN THE ENVIRONMENT, OR NO ROOM FOR
C     THE BLOCK). ARGUMENTS AS GEND'S; DT IS ZERO FROM I1 TO NJJ.
C
      INTEGER         NCARAY(1),NBARAY(1),MATOUT,IDONE,I1,I2,J1,J2,
     1                IDTPT,K,KS,NBXR,I,J,IB0,IBN,NB,NTHR,IOS,IERR
      REAL            YS(1),ZS(1),SG(1),CG(1),WORK(1)
      COMPLEX         DT(1)
      INTEGER         MCB,NROW,ND,NE,NP,NSTRIP,NTP,NJJ,NEXT,LENGTH,
     1                INC,INB,IYS,IZS,IEE,ISG,ICG,IXIC,IDELX,IXLAM,IDT,
     2                ICORE
      REAL            REFC,FMACH,RFK,F
      COMMON /AMGMN / MCB(7),NROW,ND,NE,REFC,FMACH,RFK
      COMMON /DLCOM / NP,NSTRIP,NTP,F,NJJ,NEXT,LENGTH,
     1                INC,INB,IYS,IZS,IEE,ISG,ICG,
     2                IXIC,IDELX,IXLAM,IDT,
     3                ICORE
      CHARACTER*16    ENVT
      INTEGER, ALLOCATABLE :: KSV(:)
      COMPLEX, ALLOCATABLE :: DTB(:,:)
!$    INTEGER         OMP_GET_MAX_THREADS
C
      IDONE = 0
      NTHR  = 0
      ENVT  = ' '
      CALL GETENV ('N95_DLM_THREADS',ENVT)
      IF (ENVT .NE. ' ') READ (ENVT,*,IOSTAT=IOS) NTHR
      IF (ENVT .NE. ' ' .AND. IOS .NE. 0) NTHR = 0
      IF (NTHR .EQ. 1) RETURN
!$    IF (NTHR .LE. 0) NTHR = OMP_GET_MAX_THREADS()
      IF (NTHR .LE. 0) NTHR = 1
C
      I1 = 1
      I2 = NTP
      J1 = 1
      J2 = NTP
      IDTPT = I1 + NROW
      IF (I2 .LT. I1) RETURN
C
C     THE STRIP OF EACH RECEIVING BOX, AS GEND WALKS THEM (K IS THE
C     PANEL, KS THE STRIP)
C
      ALLOCATE (KSV(I2),STAT=IERR)
      IF (IERR .NE. 0) RETURN
      K    = 1
      KS   = 1
      NBXR = NCARAY(K)
      DO 20 I = I1,I2
      KSV(I) = KS
      IF (I .EQ. I2) GO TO 20
      IF (I .EQ. NBARAY(K)) K = K + 1
      IF (I .NE. NBXR) GO TO 20
      KS   = KS + 1
      NBXR = NBXR + NCARAY(K)
   20 CONTINUE
C
C     BLOCKS OF ROWS: SIXTEEN PER THREAD, SO THE THREADS SHARE THE WORK
C     OF A BLOCK EVENLY AND THE BLOCK STAYS SMALL (2,282 BOXES, EIGHT
C     THREADS: 128 ROWS, 2.3 MB)
C
      NB = MIN(I2-I1+1,16*NTHR)
      ALLOCATE (DTB(J2,NB),STAT=IERR)
      IF (IERR .NE. 0) THEN
         DEALLOCATE (KSV)
         RETURN
      END IF
      DO 60 IB0 = I1,I2,NB
      IBN = MIN(IB0+NB-1,I2)
!$OMP PARALLEL DO NUM_THREADS(NTHR) SCHEDULE(DYNAMIC,1)
!$OMP&  DEFAULT(SHARED) PRIVATE(I)
      DO 40 I = IB0,IBN
      CALL DPPS (KSV(I),I,J1,J2,SG(KSV(I)),CG(KSV(I)),YS,ZS,NBARAY,
     1           NCARAY,DTB(1,I-IB0+1),WORK)
   40 CONTINUE
!$OMP END PARALLEL DO
      DO 50 I = IB0,IBN
      DO 45 J = J1,J2
   45 DT(IDTPT+J-1) = DTB(J,I-IB0+1)
      CALL PACK (DT,MATOUT,MCB)
   50 CONTINUE
   60 CONTINUE
      DEALLOCATE (DTB,KSV)
      IDONE = 1
      RETURN
      END
