      SUBROUTINE GUSTQ
C
C     HALO: THE GUST COLUMNS OF THE MODAL AERODYNAMICS, PER (MACH, K)
C     PAIR - NEW (NOT NASA'S): THE EXPORT TWIN OF THE SPANWISE GUST
C
C     DMAP CALLING SEQUENCE
C
C         GUSTQ  QHJL,ACPT,WGSPAN/QHGL/C,N,BREF $
C
C     AT EVERY (MACH, K) PAIR OF QHJL (AMP'S PER-BOX MATRIX, "REALLY
C     QJHL": NJ BOX ROWS, NCOL MODE COLUMNS A PAIR, THE PAIRS IN ITS
C     HEADER RECORD) AND FOR EVERY COLUMN C OF WGSPAN,
C
C         QHGL(H,C) = SUM OVER J OF QHJL(J,H) W(J,C)
C         W(J,C)    = WGSPAN(J,C) COS(GAMMA J)
C                     EXP(-I K (X J - X0 C) / BREF)
C
C     THE MODAL FORCE PER UNIT DYNAMIC PRESSURE OF A UNIT GUST ANGLE
C     (W G / V) ON COLUMN C'S SHAPE - THE DOWNWASH GUST2 FORMS, AT THE
C     PAIR'S REDUCED FREQUENCY (K = OMEGA BREF / V): X J AND
C     COS(GAMMA J) THE BOX CONTROL POINT AND DIHEDRAL GUST2 TAKES FROM
C     ACPT, X0 C ROW NJ+2 OF WGSPAN (ITS ROWS NJ+1 .. NJ+4 ARE WG, X0,
C     V, ID - SEE GUST). BREF IS THE REFERENCE SEMICHORD, REFC / 2.
C     WGSPAN PURGED: ONE COLUMN, THE UNIFORM GUST AT X0 = 0. QHGL HAS
C     NCOL ROWS AND, PAIR BY PAIR IN QHJL'S ORDER, A COLUMN PER WGSPAN
C     COLUMN; COMPLEX SINGLE, THE SUMS FORMED IN DOUBLE PRECISION.
C
      INTEGER          QHJL,ACPT,WGSP,QHGL,BUF1,BUF2,FILE,SYSBUF,
     1                 TRL(7),TRLW(7),ACDR(13),NAM(2),IZ(1),MCB(7)
      DOUBLE PRECISION SR,SI,PH,DK,DX0
      COMMON /BLANK / BREF,NOUSE(6)
      COMMON /SYSTEM/ SYSBUF
      COMMON /ZZZZZZ/ Z(1)
      COMMON /UNPAKX/ IUTYP,IUFST,IULST,IUINC
      COMMON /PACKX / IPTI,IPTO,IPFST,IPLST,IPINC
      EQUIVALENCE     (Z(1),IZ(1))
      DATA    QHJL,ACPT,WGSP,QHGL / 101,102,103,201 /
      DATA    NAM / 4HGUST,4HQ    /
C
      ICORE = KORSZ(IZ) - 2*SYSBUF - 2
      BUF1  = ICORE + 1
      BUF2  = BUF1 + SYSBUF
      IF (BREF .LE. 0.0) CALL MESAGE (-7,0,NAM)
C
C     QHJL: NJ BOX ROWS, NCT COLUMNS
C
      FILE = QHJL
      TRL(1) = QHJL
      CALL RDTRL (TRL)
      IF (TRL(1) .LT. 0) GO TO 999
      NJ  = TRL(3)
      NCT = TRL(2)
      IAM = 1
      IXC = IAM + NJ
      IACPT = IXC + NJ + 1
      IF (IACPT .GT. ICORE) GO TO 997
      DO 30 I = 1,NJ
   30 Z(IAM+I-1) = 0.0
C
C     THE BOXES' COS(GAMMA) AND CONTROL POINT X OFF ACPT, AS GUST2 TAKES
C     THEM (A 0 FOR EVERY THEORY BUT THE DOUBLET LATTICE)
C
      CALL GOPEN (ACPT,Z(BUF1),0)
      NJU  = 0
      FILE = ACPT
   40 CALL READ (*100,*100,ACPT,METH,1,0,NWR)
      GO TO (50,60,90,90,90), METH
C
C     DOUBLET LATTICE WITHOUT BODIES
C
   50 CALL READ (*998,*995,ACPT,ACDR,4,0,NWR)
      NP = ACDR(1)
      NSTRIP = ACDR(2)
      NJG = ACDR(3)
      NR = 2*NP + 5*NSTRIP + 2*NJG
      IF (IACPT+NR .GT. ICORE) GO TO 997
      CALL READ (*998,*995,ACPT,Z(IACPT),NR,1,NWR)
      IXIC  = IACPT + 2*NP + 5*NSTRIP - 1
      IDELX = IXIC + NJG
      ICG   = IACPT + 2*NP + 4*NSTRIP
      K  = 0
      KS = 0
      NBXR = IZ(IACPT)
      DO 59 I = 1,NJG
      Z(IAM+NJU+I-1) = Z(ICG+KS)
      Z(IXC+NJU+I-1) = Z(IXIC+I) + .5*Z(IDELX+I)
      IF (I .EQ. NJG) GO TO 59
      IF (I .EQ. IZ(IACPT+NP+K)) K = K + 1
      IF (I .NE. NBXR) GO TO 59
      KS = KS + 1
      NBXR = NBXR + IZ(IACPT+K)
   59 CONTINUE
      NJU = NJU + NJG
      GO TO 40
C
C     DOUBLET LATTICE WITH BODIES
C
   60 CALL READ (*998,*995,ACPT,ACDR,13,0,NWR)
      NJG = ACDR(1)
      NP  = ACDR(3)
      NB  = ACDR(4)
      NTP = ACDR(5)
      NTO = ACDR(10)
      NTZS= ACDR(11)
      NTYS= ACDR(12)
      NSTRIP = ACDR(13)
      IC  = IACPT
      IB  = IC + NP
      IB1 = IB + 2*NP
      IBS = IB1 + 2*NB
      NR  = 3*NP + 3*NB
      IF (IACPT+NR .GT. ICORE) GO TO 997
      CALL READ (*998,*995,ACPT,Z(IACPT),NR,0,NWR)
      NBEI = 0
      NBES = 0
      DO 61 I = 1,NB
      NBEI = NBEI + IZ(IB1+I-1)
      NBES = NBES + IZ(IBS+I-1)
   61 CONTINUE
      ICG  = IB + NP
      IX   = ICG + NSTRIP - 1
      IXS1 = IX + 4*NTP + 2*NBEI + NBES
      IXS2 = IXS1 + NBES
      NR = 11*NB + 4*NSTRIP
      CALL READ (*998,*995,ACPT,Z(ICG),-NR,0,NWR)
      NR = NSTRIP + 4*NTP + 2*NBEI + 3*NBES
      IF (ICG+NR .GT. ICORE) GO TO 997
      CALL READ (*998,*995,ACPT,Z(ICG),NR,1,NWR)
      IF (NTP .EQ. 0) GO TO 65
      K  = 0
      KS = 0
      NBXR = IZ(IC)
      DO 64 I = 1,NTP
      Z(IAM+NJU+I-1) = Z(ICG+KS)
      Z(IXC+NJU+I-1) = Z(IX+I)
      IF (I .EQ. NTP) GO TO 64
      IF (I .EQ. IZ(IB+K)) K = K + 1
      IF (I .NE. NBXR) GO TO 64
      KS = KS + 1
      NBXR = NBXR + IZ(IC+K)
   64 CONTINUE
   65 NJU = NJU + NTO
      IF (NTZS .EQ. 0) GO TO 80
      DO 70 I = 1,NTZS
      Z(IAM+NJU+I-1) = 1.0
      Z(IXC+NJU+I-1) = .5*(Z(IXS1+I) + Z(IXS2+I))
   70 CONTINUE
   80 NJU = NJU + NTZS + NTYS
      GO TO 40
C
C     MACH BOX, STRIP, PISTON THEORIES
C
   90 CALL READ (*998,*995,ACPT,NJG,1,1,NWR)
      NJU = NJU + NJG
      GO TO 40
  100 CALL CLOSE (ACPT,1)
      IF (NJU .NE. NJ) GO TO 996
C
C     QHJL'S HEADER: ITS NAME, NCOL (THE MODE COLUMNS A PAIR), THE PAIR
C     COUNT, THE PAIRS (MACH, K); THE COLUMNS FOLLOW
C
      FILE = QHJL
      IPR = IXC + NJ
      CALL OPEN (*999,QHJL,Z(BUF1),0)
      CALL READ (*998,*995,QHJL,Z(IPR),-2,0,NWR)
      CALL READ (*998,*995,QHJL,NCOL,1,0,NWR)
      CALL READ (*998,*995,QHJL,NPR,1,0,NWR)
      IF (NCOL.LT.1 .OR. NPR.LT.1 .OR. NCOL*NPR.NE.NCT) GO TO 996
      IF (IPR+2*NPR .GT. ICORE) GO TO 997
      CALL READ (*998,*995,QHJL,Z(IPR),2*NPR,1,NWR)
C
C     THE WEIGHTS: NJ+4 ROWS BY NCW (WGSPAN PURGED: ONES, X0 = 0)
C
      NJW = NJ + 4
      IWG = IPR + 2*NPR
      TRLW(1) = WGSP
      CALL RDTRL (TRLW)
      NCW = 1
      IF (TRLW(1) .GT. 0) NCW = TRLW(2)
      IF (NCW .LT. 1) GO TO 996
      IF (TRLW(1).GT.0 .AND. TRLW(3).NE.NJW) GO TO 996
      IW  = IWG + NJW*NCW
      IQ  = IW + 2*NJ*NCW
      IQG = IQ + 2*NJ
      IF (IQG+2*NCOL*NCW .GT. ICORE) GO TO 997
      IF (TRLW(1) .GT. 0) GO TO 110
      DO 105 J = 1,NJW
  105 Z(IWG+J-1) = 0.0
      DO 106 J = 1,NJ
  106 Z(IWG+J-1) = 1.0
      GO TO 120
  110 FILE = WGSP
      CALL GOPEN (WGSP,Z(BUF2),0)
      IUTYP = 1
      IUFST = 1
      IULST = NJW
      IUINC = 1
      DO 115 KC = 1,NCW
      IWC = IWG + (KC-1)*NJW
      CALL UNPACK (*112,WGSP,Z(IWC))
      GO TO 115
  112 DO 113 J = 1,NJW
  113 Z(IWC+J-1) = 0.0
  115 CONTINUE
      CALL CLOSE (WGSP,1)
C
C     PAIR BY PAIR: W (NJ BY NCW, COMPLEX), THEN THE MODE COLUMNS OF
C     QHJL, THEN A QHGL COLUMN PER WEIGHT COLUMN
C
  120 CALL GOPEN (QHGL,Z(BUF2),1)
      CALL MAKMCB (MCB,QHGL,NCOL,2,3)
      IPTI  = 3
      IPTO  = 3
      IPFST = 1
      IPLST = NCOL
      IPINC = 1
      DO 200 IP = 1,NPR
      DK = DBLE(Z(IPR+2*IP-1))/DBLE(BREF)
      DO 140 KC = 1,NCW
      IWC = IWG + (KC-1)*NJW
      DX0 = DBLE(Z(IWC+NJ+1))
      DO 130 J = 1,NJ
      IWJ = IW + 2*((KC-1)*NJ + J - 1)
      PH  = DK*(DBLE(Z(IXC+J-1)) - DX0)
      Z(IWJ  ) =  SNGL( DCOS(PH)*DBLE(Z(IAM+J-1))*DBLE(Z(IWC+J-1)))
      Z(IWJ+1) =  SNGL(-DSIN(PH)*DBLE(Z(IAM+J-1))*DBLE(Z(IWC+J-1)))
  130 CONTINUE
  140 CONTINUE
      DO 170 IH = 1,NCOL
      IUTYP = 3
      IUFST = 1
      IULST = NJ
      IUINC = 1
      CALL UNPACK (*145,QHJL,Z(IQ))
      GO TO 150
  145 CALL ZEROC (Z(IQ),2*NJ)
  150 DO 160 KC = 1,NCW
      SR = 0.0D0
      SI = 0.0D0
      DO 155 J = 1,NJ
      IWJ = IW + 2*((KC-1)*NJ + J - 1)
      IQJ = IQ + 2*(J-1)
      SR = SR + DBLE(Z(IQJ))*DBLE(Z(IWJ))
     1        - DBLE(Z(IQJ+1))*DBLE(Z(IWJ+1))
      SI = SI + DBLE(Z(IQJ))*DBLE(Z(IWJ+1))
     1        + DBLE(Z(IQJ+1))*DBLE(Z(IWJ))
  155 CONTINUE
      IGH = IQG + 2*((KC-1)*NCOL + IH - 1)
      Z(IGH  ) = SNGL(SR)
      Z(IGH+1) = SNGL(SI)
  160 CONTINUE
  170 CONTINUE
      DO 180 KC = 1,NCW
      CALL PACK (Z(IQG+2*(KC-1)*NCOL),QHGL,MCB)
  180 CONTINUE
  200 CONTINUE
      CALL CLOSE (QHJL,1)
      CALL CLOSE (QHGL,1)
      CALL WRTTRL (MCB)
      RETURN
C
C     ERRORS
C
  995 CALL MESAGE (-3,FILE,NAM)
  996 CALL MESAGE (-7,0,NAM)
  997 CALL MESAGE (-8,0,NAM)
  998 CALL MESAGE (-2,FILE,NAM)
  999 CALL MESAGE (-1,FILE,NAM)
      RETURN
      END
