      SUBROUTINE GUST3 (QHJK,WJ,PP,GUSTL,PDEL,PGUST,Q,NFREQ,NLOAD,
     1                  NROWJ,NCOLW,WGSP,NCW)
C
C     THE PURPOSE OF THIS ROUTINE IS TO MULTIPLY QHJK(+) BY WJ
C     FORMING PDEL
C     PDEL IS THEN MULTIPLIED BY  Q*WG*PP(W)  FORMING PGUST
C
C     HALO: NCW .GT. 0 IS THE SPANWISE GUST (GUST2): WJ HAS NCW COLUMNS
C     AT EACH FREQUENCY, ONE PER GUST CARD, SO PDEL HAS TOO (FREQUENCY
C     BY FREQUENCY, THE CARDS IN ORDER), AND EACH LOAD IS THE SUM OVER
C     THE CARDS WHOSE ID IS ITS SUBCASE'S (WORD 1 OF ITS GUSTL RECORD,
C     GUST1), EACH TIMES Q, ITS OWN WG AND THE LOAD'S PP. THE CARDS' WG
C     AND ID ARE ROWS NROWJ+1 AND NROWJ+4 OF WGSPAN (WGSP). NCW = 0: ONE
C     COLUMN A FREQUENCY AND ONE CARD A LOAD, AS IT ALWAYS WAS.
C
      INTEGER         QHJK,WJ,PP,GUSTL,PDEL,PGUST,IZ(1),SYSBUF,MCB(7),
     1                NAME(2),WGSP
      COMMON /PACKX / ITC1,ITC2,II1,JJ1,INCR1
      COMMON /UNPAKX/ ITC,II,JJ,INCR
      COMMON /SYSTEM/ SYSBUF
      COMMON /ZZZZZZ/ Z(1)
      EQUIVALENCE     (IZ(1),Z(1))
      DATA    NAME  / 4HGUST,1H3 /
C
C     INITIALIZE
C
      IBUF1 = KORSZ(IZ)- SYSBUF+1
      IBUF2 = IBUF1- SYSBUF
      IBUF3 = IBUF2- SYSBUF
      INCR1 = 1
      INCR  = 1
      IBUF4 = IBUF3- SYSBUF
      MCB(1)= QHJK
      CALL RDTRL(MCB)
      ITC  = 3
      ITC1 = ITC
      ITC2 = ITC
      CALL GOPEN (WJ,IZ(IBUF1),0)
      CALL GOPEN (QHJK,IZ(IBUF2),0)
      CALL GOPEN (PDEL,IZ(IBUF3),1)
C
C     SET UP TO PACK
C
      IT1 = 1
      JJ1 = MCB(3) / NROWJ
      NRQHJ = MCB(3)
      NTQHJ = NRQHJ*2
      CALL MAKMCB (MCB,PDEL,JJ1,2,ITC2)
      II   = 1
      IQHJ = 2*NFREQ+1
      IWJ  = IQHJ+NTQHJ
      NTWZ = NROWJ*2
      IPDEL= IWJ + NTWZ
      NTPDEL = JJ1*2
      NZ = IBUF4-1 - IPDEL + 2*JJ1
      IF (NZ  .LT. 0) CALL MESAGE (-8,0,NAME)
C     HALO: THE WJ COLUMNS A FREQUENCY
      NC1 = MAX0(NCW,1)
      DO 100 I = 1,NFREQ
      JJ = NRQHJ
      CALL UNPACK (*10,QHJK,Z(IQHJ))
C
C     MULTIPY EACH IMAGINARY PART BY K
C
      DO 5 J = 1,NTQHJ,2
      Z(IQHJ+J) = Z(IQHJ+J)*Z(2*I)
   5  CONTINUE
      GO TO 20
C
C     NULL COLUMN
C
   10 CALL ZEROC (Z(IQHJ),NTQHJ)
   20 CONTINUE
C
C     BRING WJ COLUMN INTO CORE
C     HALO: EACH OF THE NC1 COLUMNS OF THIS FREQUENCY IN TURN
C
      DO 90 IC = 1,NC1
      JJ = NROWJ
      CALL UNPACK (*30,WJ,Z(IWJ))
      GO TO 40
   30 CALL ZEROC (Z(IWJ),NTWZ)
   40 CONTINUE
C
C     MULTIPLY
C
      CALL GMMATC (Z(IQHJ),JJ1,NROWJ,0,Z(IWJ),NROWJ,1,0,Z(IPDEL))
      CALL PACK (Z(IPDEL),PDEL,MCB)
   90 CONTINUE
  100 CONTINUE
      CALL CLOSE (WJ,1)
      CALL CLOSE (QHJK,1)
      CALL CLOSE (PDEL,1)
      CALL WRTTRL (MCB)
      CALL DMPFIL (-PDEL,Z,NZ)
      IF (NCW .GT. 0) GO TO 500
C
C     REPEATEDLY READ PDEL MULTIPLYING BY Q,WG, AND PP
C
      CALL GOPEN (PDEL,IZ(IBUF1),0)
      CALL GOPEN (PP,IZ(IBUF2),0)
      CALL GOPEN (GUSTL,IZ(IBUF3),0)
      CALL GOPEN (PGUST,IZ(IBUF4),1)
      CALL MAKMCB (MCB,PGUST,MCB(3),MCB(4),MCB(5))
      DO 400 I = 1,NLOAD
      CALL REWIND (PDEL)
      CALL SKPREC (PDEL,1)
      CALL FREAD (GUSTL,IZ,5,1)
      IZ2 = 2
      QWG = Q*Z(IZ2+1)
      DO 300 J = 1,NFREQ
      JJ = 1
      CALL UNPACK (*310,PP,Z)
      QWGR = QWG * Z(1)
      QWGC = QWG * Z(IZ2)
      GO TO 320
  310 CONTINUE
      QWGR = 0.0
      QWGC = 0.0
  320 CONTINUE
      JJ = JJ1
      CALL UNPACK (*330,PDEL,Z)
      GO TO 340
  330 CALL ZEROC (Z,NTPDEL)
  340 CONTINUE
      DO 350 M = 1,NTPDEL,2
      PGR = QWGR*Z(M  ) - QWGC*Z(M+1)
      PGC = QWGR*Z(M+1) + QWGC*Z(M  )
      Z(M  ) = PGR
      Z(M+1) = PGC
  350 CONTINUE
      CALL PACK (Z,PGUST,MCB)
  300 CONTINUE
  400 CONTINUE
      GO TO 700
C
C     HALO: THE SPANWISE GUST. THE CARDS' WG AND ID OFF WGSPAN (ROWS
C     NROWJ+1 .. NROWJ+4: WG, X0, V, ID), THEN EACH LOAD AT EACH
C     FREQUENCY THE SUM OVER ITS CARDS OF Q WG PP PDEL (THE FIRST CARD'S
C     TERM ASSIGNED, THE REST ADDED: ONE CARD GIVES THE COLUMN ABOVE TO
C     THE BIT). A CARD NOT OF THE LOAD'S ID IS SKIPPED; A LOAD WITH NO
C     CARD (NO GUST IN ITS SUBCASE) IS NULL, AS ITS WG OF 0 MADE IT.
C
  500 IWG  = 1
      ISD  = IWG + NCW
      IACC = ISD + NCW
      ICOL = IACC + NTPDEL
      IF (ICOL+NTPDEL+8 .GT. IBUF4) CALL MESAGE (-8,0,NAME)
      CALL GOPEN (WGSP,IZ(IBUF1),0)
      ITC = 1
      II  = NROWJ + 1
      JJ  = NROWJ + 4
      DO 510 IC = 1,NCW
      CALL UNPACK (*505,WGSP,Z(ICOL))
      GO TO 508
  505 CALL ZEROC (Z(ICOL),4)
  508 Z(IWG+IC-1) = Z(ICOL)
      Z(ISD+IC-1) = Z(ICOL+3)
  510 CONTINUE
      CALL CLOSE (WGSP,1)
      ITC = 3
      II  = 1
      CALL GOPEN (PDEL,IZ(IBUF1),0)
      CALL GOPEN (PP,IZ(IBUF2),0)
      CALL GOPEN (GUSTL,IZ(IBUF3),0)
      CALL GOPEN (PGUST,IZ(IBUF4),1)
      CALL MAKMCB (MCB,PGUST,MCB(3),MCB(4),MCB(5))
      DO 600 I = 1,NLOAD
      CALL REWIND (PDEL)
      CALL SKPREC (PDEL,1)
      CALL FREAD (GUSTL,IZ(ICOL),5,1)
      ISET = IZ(ICOL)
      DO 590 J = 1,NFREQ
      JJ = 1
      CALL UNPACK (*520,PP,Z(ICOL))
      PPR = Z(ICOL)
      PPI = Z(ICOL+1)
      GO TO 525
  520 PPR = 0.0
      PPI = 0.0
  525 NHIT = 0
      DO 570 IC = 1,NCW
      IF (ISET.EQ.0 .OR. NINT(Z(ISD+IC-1)).NE.ISET) GO TO 565
      QWG  = Q*Z(IWG+IC-1)
      QWGR = QWG * PPR
      QWGC = QWG * PPI
      JJ = JJ1
      CALL UNPACK (*530,PDEL,Z(ICOL))
      GO TO 535
  530 CALL ZEROC (Z(ICOL),NTPDEL)
  535 DO 550 M = 1,NTPDEL,2
      PGR = QWGR*Z(ICOL+M-1) - QWGC*Z(ICOL+M)
      PGC = QWGR*Z(ICOL+M) + QWGC*Z(ICOL+M-1)
      IF (NHIT .GT. 0) GO TO 540
      Z(IACC+M-1) = PGR
      Z(IACC+M  ) = PGC
      GO TO 550
  540 Z(IACC+M-1) = Z(IACC+M-1) + PGR
      Z(IACC+M  ) = Z(IACC+M  ) + PGC
  550 CONTINUE
      NHIT = NHIT + 1
      GO TO 570
  565 CALL SKPREC (PDEL,1)
  570 CONTINUE
      IF (NHIT .EQ. 0) CALL ZEROC (Z(IACC),NTPDEL)
      CALL PACK (Z(IACC),PGUST,MCB)
  590 CONTINUE
  600 CONTINUE
  700 CALL CLOSE (PDEL,1)
      CALL CLOSE (PP,1)
      CALL CLOSE (GUSTL,1)
      CALL CLOSE (PGUST,1)
      CALL WRTTRL (MCB)
      RETURN
      END
