      SUBROUTINE LSPLND (NI,XI,ND,XD,DZ,G,NCORE,ISNG)
C
C     HALO: MINTRP'S SPLINE THROUGH A LIST OF REDUCED FREQUENCIES, IN
C     DOUBLE PRECISION - WHAT LSPLIN COMPUTES FOR THE CASE AERO 11 USES
C     (ADRI FOR THE GUST MATRIX QHJ, FRD2I FOR QHH): KY = 1 (THE KERNEL
C     AND ITS IMAGE IN K = 0, SO THE FIT IS EVEN IN K), KD = 0, KT = 1,
C     NO SLOPE TERMS (DTX, DTY < 0), EVERY X ZERO, ONE CONSTANT TERM.
C     FOR TARGET D THE WEIGHTS W(I,D) OF THE NI TABULATED K ARE THE
C     FIRST NI COMPONENTS OF A**-1 R(D), WHERE
C
C        A = | K(YI,YJ)+DZ*DELTA(I,J)  1 |    R(D) = | K(YD,YI) |
C            | 1                       0 |           | 1        |
C
C        K(A,B) = (ABS(A-B)**3 + ABS(A+B)**3) / 12
C
C     AS LSPLIN'S INVERS AND GMMATS GIVE THEM, BUT SOLVED BY GAUSSIAN
C     ELIMINATION WITH PARTIAL PIVOTING IN DOUBLE PRECISION. LSPLIN
C     SOLVES IN SINGLE PRECISION, AND THE CUBIC KERNEL'S SYSTEM IS
C     ILL-CONDITIONED WHEN K VALUES LIE CLOSE (A K LIST STARTING 0.005,
C     0.01, 0.02 AND THEIR IMAGES): ITS WEIGHTS CAME OUT OF ORDER 10,
C     OSCILLATING, AND NOT 1 AT A TABULATED K. A GUST MATRIX WHOSE
C     IMAGINARY PART BENDS AT LOW K (ITS BOXES FAR AFT) WAS THEN OFF BY
C     UP TO 70 % EVEN AT THE TABULATED K, AND THE GUST RESPONSE WAS
C     JAGGED FROM ONE FREQUENCY TO THE NEXT.
C
C     G IS MINTRP'S OPEN CORE: THE WEIGHTS ARE RETURNED IN ITS FIRST
C     ND*NI WORDS (REAL, NI TO A TARGET, AS LSPLIN RETURNS THEM) AND THE
C     DOUBLE PRECISION WORK LIES ABOVE THEM. ISNG = 1, OR 2 WHEN THE
C     SYSTEM IS SINGULAR (TWO EQUAL K), AS INVERS REPORTS IT.
C
      INTEGER         NI,ND,NCORE,ISNG,N,NW,IW,NEED
      REAL            XI(1),XD(1),DZ,G(1)
      INTEGER         NAME(2)
      DATA    NAME  / 4HLSPL,4HND   /
      N    = NI + 1
      NW   = ND*NI
      IW   = NW + 1
      IF (MOD(NW,2) .NE. 0) IW = NW + 2
      NEED = IW - 1 + 2*(N*N + N*ND)
      IF (NEED .GT. NCORE) CALL MESAGE (-8,0,NAME)
      CALL LSPLN1 (NI,N,XI,ND,XD,DZ,G(IW),G(IW+2*N*N),G,ISNG)
      RETURN
      END

      SUBROUTINE LSPLN1 (NI,N,XI,ND,XD,DZ,A,B,W,ISNG)
C
C     HALO: LSPLND'S SOLVE (A AND B DOUBLE PRECISION WORK IN MINTRP'S
C     OPEN CORE, W THE REAL WEIGHTS)
C
      INTEGER          NI,N,ND,ISNG,I,J,K,IP,L
      REAL             XI(1),XD(1),DZ,W(NI,ND)
      DOUBLE PRECISION A(N,N),B(N,ND),YA,YB,T,AMAX,S
C
C     THE SYSTEM AND ITS RIGHT HAND SIDES
C
      DO 20 J = 1,NI
      YB = DBLE(XI(2*J))
      DO 10 I = 1,NI
      YA = DBLE(XI(2*I))
      A(I,J) = (ABS(YA-YB)**3 + ABS(YA+YB)**3)/12.D0
   10 CONTINUE
      A(J,J) = A(J,J) + DBLE(DZ)
      A(N,J) = 1.D0
      A(J,N) = 1.D0
   20 CONTINUE
      A(N,N) = 0.D0
      DO 40 L = 1,ND
      YA = DBLE(XD(2*L))
      DO 30 I = 1,NI
      YB = DBLE(XI(2*I))
      B(I,L) = (ABS(YA-YB)**3 + ABS(YA+YB)**3)/12.D0
   30 CONTINUE
      B(N,L) = 1.D0
   40 CONTINUE
C
C     ELIMINATION WITH PARTIAL PIVOTING
C
      DO 100 K = 1,N
      IP   = K
      AMAX = ABS(A(K,K))
      DO 50 I = K+1,N
      IF (ABS(A(I,K)) .LE. AMAX) GO TO 50
      AMAX = ABS(A(I,K))
      IP   = I
   50 CONTINUE
      IF (AMAX .EQ. 0.D0) GO TO 900
      IF (IP .EQ. K) GO TO 70
      DO 60 J = K,N
      T       = A(K,J)
      A(K,J)  = A(IP,J)
      A(IP,J) = T
   60 CONTINUE
      DO 65 L = 1,ND
      T       = B(K,L)
      B(K,L)  = B(IP,L)
      B(IP,L) = T
   65 CONTINUE
   70 DO 90 I = K+1,N
      T = A(I,K)/A(K,K)
      IF (T .EQ. 0.D0) GO TO 90
      DO 80 J = K+1,N
      A(I,J) = A(I,J) - T*A(K,J)
   80 CONTINUE
      DO 85 L = 1,ND
      B(I,L) = B(I,L) - T*B(K,L)
   85 CONTINUE
   90 CONTINUE
  100 CONTINUE
C
C     BACK SUBSTITUTION, AND THE WEIGHTS OF THE TABULATED K
C
      DO 130 L = 1,ND
      DO 120 K = N,1,-1
      S = B(K,L)
      DO 110 J = K+1,N
      S = S - A(K,J)*B(J,L)
  110 CONTINUE
      B(K,L) = S/A(K,K)
  120 CONTINUE
      DO 125 I = 1,NI
      W(I,L) = SNGL(B(I,L))
  125 CONTINUE
  130 CONTINUE
      ISNG = 1
      RETURN
  900 ISNG = 2
      RETURN
      END

      INTEGER FUNCTION MINTDQ (ISET)
C
C     HALO: WHETHER MINTRP SOLVES ITS K SPLINE IN DOUBLE PRECISION
C     (LSPLND): ISET 1 ASKS FOR IT, 0 GOES BACK TO LSPLIN, -1 ONLY
C     ASKS. ADRI AND FRD2I SET IT AROUND THEIR CALL; EVERY OTHER CALLER
C     OF MINTRP (FA1K'S K METHOD) KEEPS LSPLIN AND ITS BITS.
C
      INTEGER ISET,ISTATE
      SAVE    ISTATE
      DATA    ISTATE / 0 /
      IF (ISET .GE. 0) ISTATE = ISET
      MINTDQ = ISTATE
      RETURN
      END
