      SUBROUTINE MMA10X (D,A,B,N)
C
C     HALO: THE INNER LOOP OF MMA104'S "A NON-TRANSPOSED" PRODUCT (LOOP
C     4400) - D(K) = D(K) + A(K)*B FOR K = 1..N, COMPLEX DOUBLE - WITH
C     THE ARRAYS AS ARGUMENTS OF THEIR OWN. MMA104 TAKES ONE OPEN-CORE
C     ARRAY AS THREE DUMMIES (ZI, ZD, ZDC), SO IT CANNOT BE OPTIMISED;
C     THIS IS, AT -O2 -FFP-CONTRACT=OFF: THE SAME OPERATIONS IN THE SAME
C     ORDER (THE COMPLEX PRODUCT, THEN THE SUM), SO THE SAME BITS.
C
      INTEGER         N,K
      DOUBLE COMPLEX  D(N),A(N),B
      DO 10 K = 1,N
      D(K) = D(K) + A(K)*B
   10 CONTINUE
      RETURN
      END

      SUBROUTINE MMA10D (ACC,A,B,N)
C
C     HALO: THE INNER LOOP OF MMA104'S "A TRANSPOSED" PRODUCT (LOOP
C     44000) - ACC = ACC + A(K)*B(K) FOR K = 1..N IN THAT ORDER, COMPLEX
C     DOUBLE - AS MMA10X. IN A FLUTTER RUN THIS IS QIH = GKI(T)*QKH PER
C     REDUCED FREQUENCY, A DOT PRODUCT OF THE K-SET LENGTH FOR EVERY
C     (MODE, MODE) PAIR, AND THE LARGEST SERIAL PIECE OF AMP LEFT.
C
      INTEGER         N,K
      DOUBLE COMPLEX  ACC,A(N),B(N),S
      S = ACC
      DO 10 K = 1,N
      S = S + A(K)*B(K)
   10 CONTINUE
      ACC = S
      RETURN
      END
