      SUBROUTINE N95DOT (ACC,A,B,N,ISGN)
C
C     HALO: THE INNER PRODUCTS OF DECOMP (LOOP 810) AND MMA112 (LOOP
C     24000), AS THEIR OWN LOOPS DO THEM: ACC = ACC + A(K)*B(K)
C     (ISGN = 1) OR ACC = ACC - A(K)*B(K) (ISGN = -1), K = 1..N IN
C     ORDER, DOUBLE PRECISION. AT -O0 THOSE LOOPS KEEP ACC IN MEMORY;
C     HERE IT IS IN A REGISTER (-O2 -FFP-CONTRACT=OFF): THE SAME
C     OPERATIONS, THE SAME BITS. THE CALLERS CHECK THAT ACC IS NOT ONE
C     OF THE A OR B TERMS.
C
      INTEGER          N,ISGN,K
      DOUBLE PRECISION ACC,A(N),B(N),S
      S = ACC
      IF (ISGN .LT. 0) GO TO 20
      DO 10 K = 1,N
      S = S + A(K)*B(K)
   10 CONTINUE
      ACC = S
      RETURN
   20 DO 30 K = 1,N
      S = S - A(K)*B(K)
   30 CONTINUE
      ACC = S
      RETURN
      END

      SUBROUTINE FERXTQ (V2,V3,ZV,NORD,NORTHO,SDMAX)
C
C     HALO: FERXTD'S REORTHOGONALISATION AGAINST THE VECTORS IN CORE
C     (ITS LOOPS 1080-1110): FOR EACH OF THE NORTHO VECTORS ZV(.,IY),
C     SD = V3 . ZV(.,IY) SUMMED IN ORDER, SDMAX = MAX |SD|, AND
C     V2 = V2 - SD*ZV(.,IY). THE SAME OPERATIONS IN THE SAME ORDER AT
C     -O2 -FFP-CONTRACT=OFF (THE UPDATE VECTORISES; THE SUM DOES NOT),
C     SO THE SAME BITS.
C
      INTEGER          NORD,NORTHO,I,IY
      DOUBLE PRECISION V2(NORD),V3(NORD),ZV(NORD,NORTHO),SDMAX,SD
      DO 30 IY = 1,NORTHO
      SD = 0.0D0
      DO 10 I = 1,NORD
      SD = SD + V3(I)*ZV(I,IY)
   10 CONTINUE
      IF (DABS(SD) .GT. SDMAX) SDMAX = DABS(SD)
      DO 20 I = 1,NORD
      V2(I) = V2(I) - SD*ZV(I,IY)
   20 CONTINUE
   30 CONTINUE
      RETURN
      END
